### ISSUE TITLE
Improve Readme

### ISSUE THREAD

**Issue by jairodemorais** [crazycodeboy/react-native-splash-screen#1]
hi @crazycodeboy thanks for this useful code, but I got some problem during the setup.

would be great if u cool add the java imports of each file in the Readme file, because u just added the code. I had to review ur examples code to notice that:

in mainApplication.java I must include:

`import com.cboy.rn.splashscreen.SplashScreenReactPackage;`

and in mainActivity.java

`import android.os.Bundle;
import com.cboy.rn.splashscreen.SplashScreen;`

Also u mention adding

`Go to node_modules ➜ react-native-launch-image and add SplashScreen.xcodeproj`

I suspect that u had renamed ur component from **react-native-launch-image** to **react-native-splash-screen** and u forgot update this line right?

Last thing, is that I was not able to render the splash screen in IOS, where should I put the image to be rendered by IOS, should I add some xml file like we did for android? in the Readme getting started u only mention Adroid :(

**Comment by crazycodeboy** [comment]
Thanks for your feedback. You can get help by looking at the [example](https://github.com/crazycodeboy/react-native-splash-screen/tree/master/examples).
