### ISSUE TITLE
[Android] React native 0.37. First shows white splash screen and after 1 sec shows my splash screen.

### ISSUE THREAD

**Issue by grundmanise** [crazycodeboy/react-native-splash-screen#11]
Android.
React native 0.37.

First shows white (default) splash screen and after 1 sec shows my splash screen.
Is it normal behaviour? How can I fix it?

**Comment by crazycodeboy** [comment]
In your MainActivity.java, `SplashScreen.show(this); ` must in the above `super.onCreate(savedInstanceState);`.
```
public class MainActivity extends ReactActivity {
   @Override
    protected void onCreate(Bundle savedInstanceState) {
        SplashScreen.show(this);  // here
        super.onCreate(savedInstanceState);
    }
    // ...other code
}
```

**Comment by grundmanise** [comment]
Everything is like in your comment above, but I still see the white bg and after that my splash screen shows.

Actually I found a fix for it:
http://stackoverflow.com/a/34960302/4541800

You could include it in the readme.

Thanks!

**Comment by jasan-s** [comment]
@grundmanise , was pulling my hair looking into the native code. thanks for the link. solved the white screen issue.

**Comment by liptonzuma** [comment]
This fixed mine also.
