### ISSUE TITLE
Android build error. MainActivity.java:7: error: cannot find symbol - onCreate(Bundle savedInstanceState)

### ISSUE THREAD

**Issue by brkrtp** [crazycodeboy/react-native-splash-screen#111]
"react": "16.0.0-alpha.12",
"react-native": "0.47.0",
"react-native-splash-screen": "^3.0.1"
**Build console:**
<img width="566" alt="screen shot 2017-10-15 at 14 57 01" src="https://user-images.githubusercontent.com/18514716/31584553-266116c2-b1b9-11e7-99a6-449d3eb5cd5a.png">
**MainActivity.java;**
<img width="407" alt="screen shot 2017-10-15 at 14 58 08" src="https://user-images.githubusercontent.com/18514716/31584559-4b790eec-b1b9-11e7-9ca3-c3dad8a2eeba.png">

**Comment by brkrtp** [comment]
İm solved [https://github.com/react-native-component/react-native-smart-splash-screen/issues/20](url)

**Comment by brandonjyuhas** [comment]
@brkrtp I'm experiencing the same error. The link in your latest comment is broken for me (404). What did you do to fix the issue?

**Comment by jnranawedo** [comment]
Hello, Have you found any solution for this ?

**Comment by brandonjyuhas** [comment]
@jnranawedo in my case, I wasn't including `Bundle` in `android/app/src/main/java/com/<myapp>/MainActivity.java`.

I solved the issue by adding these lines to the top of `MainActivity.java`:

```
import android.os.Bundle; // required for onCreate parameter
import org.devio.rn.splashscreen.SplashScreen; // required for react-native-splash-screen >= 0.3.1
```

**Comment by Salman98** [comment]
this might help you 
MainActivity.java


 import android.os.Bundle;
import com.facebook.react.ReactActivity;
import com.cboy.rn.splashscreen.SplashScreen;

public class MainActivity extends ReactActivity {
   @Override
    protected void onCreate(Bundle savedInstanceState) {
        SplashScreen.show(this);  // here
        super.onCreate(savedInstanceState);
    }
    // ...other code
}

**Comment by kg-currenxie** [comment]
Yes, how is this not in the docs (still!)?

**Comment by bhaskardabhi** [comment]
I am getting 

```
/{PathToFile}/MainApplication.java:55: error: incompatible types: MainApplication cannot be converted to Activity
    SplashScreen.show(this);
```

My file is like below:

```
package com.testApp;

import android.app.Application;
import android.os.Bundle;
import com.facebook.react.ReactActivity;
import com.facebook.react.ReactApplication;
import org.devio.rn.splashscreen.SplashScreen;
import org.devio.rn.splashscreen.SplashScreenReactPackage;
import com.facebook.soloader.SoLoader;

public class MainApplication extends Application implements ReactApplication {

    @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new MainReactPackage(),
            new SplashScreenReactPackage()
      );
    }

  @Override
  public void onCreate() {
    SplashScreen.show(this);
    super.onCreate();
    SoLoader.init(this,  false); // 
  }
}



```

**Comment by saikrishna407** [comment]
Yes it's Working 
Just Add the this line given that document.
MainActivity.java file
-----------------------

"import android.os.Bundle;"

Thankyou...

**Comment by re-ali** [comment]
Yes, add this line on the top of MainActivity.java file
import android.os.Bundle; // required for onCreate parameter

**Comment by karladler** [comment]
`import android.os.Bundle;`

should be aded to the README, since it's by default not added in main activity file.
