### ISSUE TITLE
black splash screen on iOS

### ISSUE THREAD

**Issue by YasirPanjsheri** [crazycodeboy/react-native-splash-screen#119]
I am getting black screen instead of splash screen in iOS. Im not sure what I did wrong. I managed to make it work for android. I am using xcode 9.0.1
There is only example for customizing splashscreen on iOS, and I didn't understand it. so this is what I did: 

In my project on xcode `general` under `App Icons and Launch Images` I pressed `User Asset Catalog` and then pressed `Migrate` when prompted. 

On `Launch Screen File` I deleted the line `LaunchScreen` and left it blank. I have no `LaunchScreen.xib`. Within the `Images.xcassets` there is now the option `LaunchImage` , so I dragged splash screen:

![screen shot 2017-11-01 at 16 05 09](https://user-images.githubusercontent.com/12644122/32273064-8576be2e-bf1e-11e7-82b9-c7f988077cb3.png)

can someone help? thanx

**Comment by sina-mirhejazi** [comment]
Can you please describe how you fixed your problem?
I have the same issue and I don't know what's wrong

**Comment by namxam** [comment]
@YasirPanjsheri Yeah, would be awesome if you could share your solution. Having the same issue.

**Comment by namxam** [comment]
Ok, I solved it by clearing the `Launch Screen File` field. It contained the name of the xib which i deleted. After clearing it and rebuilding the project, my custom splash screen was shown.

<img width="878" alt="screen shot 2017-11-20 at 11 05 40" src="https://user-images.githubusercontent.com/5399/33013073-09362402-cde3-11e7-947a-fe2d456d6460.png">

**Comment by sina-mirhejazi** [comment]
Thank you
This solved my issue

**Comment by assafb81** [comment]
I tried this  fix, and I can see the splash screen
but now the entire screen has "shrank" - I have 2 black lines on top and at the bottom of my iPhone device which hide part of my content

**Comment by darekg11** [comment]
If have changed your Splash Screen image inside `LaunchScreen.xib` to different one but under the same name then you must restart Your IOS device otherwise you will have a black screen.  
https://stackoverflow.com/questions/33002829/ios-keeping-old-launch-screen-and-app-icon-after-update

**Comment by vadiveldivum** [comment]
try this one 
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  
  
  
  

  NSURL *jsCodeLocation;

  jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
  RCTRootView *rootView = [[RCTRootView alloc] initWithBundleURL:jsCodeLocation
                                                      moduleName:@"TestAPP"
                                               initialProperties:nil
                                                   launchOptions:launchOptions];

  

  UIImageView *backgroundImage = [[UIImageView alloc] initWithImage:[UIImage imageNamed:@"Splash_screen"]];
  backgroundImage.frame=[[UIScreen mainScreen] bounds];
  backgroundImage.contentMode = UIViewContentModeScaleAspectFill;

  
  
  rootView.backgroundColor = [UIColor clearColor];

  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  
  
  UIViewController *rootViewController = [UIViewController new];
 
  [rootView addSubview:backgroundImage];
  [rootView sendSubviewToBack:backgroundImage];
   rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];
  return YES;
}

**Comment by HusseinElGanzory** [comment]
> * [rootView addSubview:backgroundImage];



> try this one
> 
> * (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
>   {
>   NSURL *jsCodeLocation;
>   jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
>   RCTRootView *rootView = [[RCTRootView alloc] initWithBundleURL:jsCodeLocation
>   moduleName:@"TestAPP"
>   initialProperties:nil
>   launchOptions:launchOptions];
>   UIImageView *backgroundImage = [[UIImageView alloc] initWithImage:[UIImage imageNamed:@"Splash_screen"]];
>   backgroundImage.frame=[[UIScreen mainScreen] bounds];
>   backgroundImage.contentMode = UIViewContentModeScaleAspectFill;
>   rootView.backgroundColor = [UIColor clearColor];
>   self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
>   UIViewController *rootViewController = [UIViewController new];
>   [rootView addSubview:backgroundImage];
>   [rootView sendSubviewToBack:backgroundImage];
>   rootViewController.view = rootView;
>   self.window.rootViewController = rootViewController;
>   [self.window makeKeyAndVisible];
>   return YES;
>   }

i used code about but splash not hide why ?

**Comment by jamesdarabi** [comment]
I realized the image I was trying to use was way too big. After I reduced the file size of the image I was using for the background of my launch screen, everything worked as expected. Not sure if this is the same issue, but I was getting the black launch screen so perhaps this will help someone else.

**Comment by Monir-Shembesh** [comment]
@jamesdarabi i am getting black screen then my app launches. I think i may be using large images too. I dont have an image fo the background i only have ones for the logo. what are the sizes you used?

**Comment by ilyas-shah** [comment]
In my case, I fixed using this: https://www.hackingwithswift.com/example-code/uikit/how-to-fix-the-error-failed-to-instantiate-the-default-view-controller-for-uimainstoryboardfile

**Comment by ilyas-shah** [comment]
In my case, I fixed using this: https://www.hackingwithswift.com/example-code/uikit/how-to-fix-the-error-failed-to-instantiate-the-default-view-controller-for-uimainstoryboardfile

**Comment by RanaAwais3553** [comment]
There are multi reasons of black splash as a launch screen in react native iOS 
**First Scenario** 
1-  Open iOS project in Xcode 
2- Select your Project and in right section 
3- Go to **General** First tab in top tab Bar  in body of Xcode.
4- Set your .storyBoard file in **Launch Screen File** section
  
<img width="1107" alt="Screenshot 2022-02-17 at 14 59 58" src="https://user-images.githubusercontent.com/67045405/154454034-e8a79a3d-3a4a-48d6-9f15-00fdabb6b26f.png">

**Second Scenario**

1- Got to File --> workspace setting.. --> derivedData --> delete deriveData folder from your iOS project.
2- uninstall app from your device or simulator.
3- Clean Build Folder
4- Reboot or restart your iOS device or simulator
5- run your project again.

**Third Scenario**

1- run your project from xcode 
2- Click on the warning tab Icon from left most section top tab bar.
3- See if there is warning related to the launchScreen, clear this warning and proceed second Scenario again.


                                                                                    **Happy Coding Just Cheer**

**Comment by jokerhp6789** [comment]
<img width="1214" alt="image" src="https://user-images.githubusercontent.com/59762943/189564139-f3d6f0f2-54d1-4a95-a30d-0fc42ef087ce.png">
in my case , adding the LaunchScreen.storyboard  file to copy bundle resource in Build Phase make the splash screen display

**Comment by utpalkoley** [comment]
> I realized the image I was trying to use was way too big. After I reduced the file size of the image I was using for the background of my launch screen, everything worked as expected. Not sure if this is the same issue, but I was getting the black launch screen so perhaps this will help someone else.

This worked for me.

**Comment by francoangulo** [comment]
> Ok, I solved it by clearing the `Launch Screen File` field. It contained the name of the xib which i deleted. After clearing it and rebuilding the project, my custom splash screen was shown.
> 
> <img alt="screen shot 2017-11-20 at 11 05 40" width="878" src="https://user-images.githubusercontent.com/5399/33013073-09362402-cde3-11e7-947a-fe2d456d6460.png">

You saved my day! This worked for me!

**Comment by Csutkas** [comment]
For me the splash appeared as a black screen because the image file size was too big (like 4-6MB).
I added a new set with file size around 100kb and now works perfectly!
