### ISSUE TITLE
No splash screen appears

### ISSUE THREAD

**Issue by aditya-simplecrm** [crazycodeboy/react-native-splash-screen#136]
I followed all the steps as given but no splash screen is coming on android and ios.

SplashScreen.show() is undefined and then app crashes
SplashScreen.hide() is also undefined

react-native-cli: 2.0.1
react-native: 0.50.4

**Comment by andresubri** [comment]
Did you made sure that the library was properly linked? show() goes on native and hide() goes on your JS.

**Comment by aditya-simplecrm** [comment]
@andresubri Yes library is installed properly and now the app is crashing after reinstalling the app again.
App is crashing on app launch.

**Comment by andresubri** [comment]
Check this out 
https://github.com/crazycodeboy/react-native-splash-screen/issues/124

**Comment by aditya-simplecrm** [comment]
@andresubri Thanks for the help. Issue is fixed now.
