### ISSUE TITLE
android明显还是有空白 为什么不是用主题背景图片的方式？

### ISSUE THREAD

**Issue by 277850318** [crazycodeboy/react-native-splash-screen#14]

**Comment by crazycodeboy** [comment]
```
public class MainActivity extends ReactActivity {
   @Override
    protected void onCreate(Bundle savedInstanceState) {
        SplashScreen.show(this);  // here
        super.onCreate(savedInstanceState);
    }
    // ...other code
}
```
` SplashScreen.show(this);  // here`要在` super.onCreate(savedInstanceState);`之前设置

**Comment by 277850318** [comment]
![screenflow](https://cloud.githubusercontent.com/assets/8946022/21320082/c2c6326e-c64a-11e6-885b-32fb0fc8fd19.gif)

**Comment by crazycodeboy** [comment]
这个白屏是因为主题引起的，你设置主题为透明就可以了

**Comment by 277850318** [comment]
果然 少了一行配置 这组件已经完美了 建议在readme里加上提示
<style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
        
        
        <item name="android:windowIsTranslucent">true</item>
    </style>

**Comment by 277850318** [comment]
还是建议使用主题的方式  
我发现 现有方式 点app图标启动的时候 还没打开启动页前
会有一个短暂的卡顿
主题的方式没有  那才是真正的秒开
