### ISSUE TITLE
setTimeout(SplashScreen.hide(), 5000)报错

### ISSUE THREAD

**Issue by woshizhoujie** [crazycodeboy/react-native-splash-screen#140]
为什么SplashScreen.hide() 一添加setTimeout就会报如下错误
![image](https://user-images.githubusercontent.com/24771453/33697772-9bb04c28-db43-11e7-9883-f3c180e627a8.png)
![image](https://user-images.githubusercontent.com/24771453/33697787-b5544062-db43-11e7-8099-f842aff3a956.png)

**Comment by xinwanggit** [comment]
setTimeout(()=>{SplashScreen.hide()}, 5000)
settimeout第一个参数为函数
