### ISSUE TITLE
android启动页怎么设置全屏显示了

### ISSUE THREAD

**Issue by 277850318** [crazycodeboy/react-native-splash-screen#15]

**Comment by 277850318** [comment]
show(this,true);就是全屏  感觉文档没写全啊  非得看下源码才能知道。。。

**Comment by youngjuning** [comment]
@277850318 thanks bro

**Comment by ShuChangSC** [comment]
@277850318 Thanks

**Comment by guohuihot** [comment]
图片上方怎么还有个状态栏是个什么，有wifi,蓝牙，电池。。。信息

**Comment by guohuihot** [comment]
![1](https://user-images.githubusercontent.com/3119995/62667777-c4020380-b9bb-11e9-9f19-3189690be459.png)
这个怎么隐藏

**Comment by BAE86AEC1946B6AB60CCD7452DC811F0** [comment]
> SplashScreen.show(this,true)就是全屏 感觉文档没写全啊 非得看下源码才能知道。。。

刘海屏依旧无法全屏
