### ISSUE TITLE
IPhoneX SafeArea isn´t considered?!

### ISSUE THREAD

**Issue by BigPun86** [crazycodeboy/react-native-splash-screen#151]
Hey there!

Somehow this breaks iPhoneX View and the View looks weird. So somehow we might need to consider any SafeAreaView Options. If someone can give me some hints i will fix it and create a PR

<img width="368" alt="screen shot 2017-12-31 at 01 22 54" src="https://user-images.githubusercontent.com/7880624/34469370-bf0e745e-ef1d-11e7-9b07-0e49ef51b78b.png">

**Comment by sagark1510** [comment]
@BigPun86 Hi may I know your how your `Contents.json` file looks alike coz I am having the same issue and adding 1125x2436 isn't working.

**Comment by trangcongthanh** [comment]
@sagark1510 You need check "iOS 8 or later" for support iPhone X
<img width="260" alt="iphone-x-splash-screen" src="https://user-images.githubusercontent.com/14819342/39359542-a21eb8e0-4a44-11e8-8d1b-5dd41d827ad7.png">
