### ISSUE TITLE
Android 4.X crashed java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by Symous** [crazycodeboy/react-native-splash-screen#152]
Hi,awesome lib! (碉堡了，老哥)

I have found that when I run my app on Android 4.4 the app crashed and the error in android studio logcat print this:
java.lang.NoClassDefFoundError: com.cboy.rn.splashscreen.SplashScreen$1

It works well on Android 5+ and iOS.

**Comment by shi1hh** [comment]
这个应该是4.4系统方法数什么的6655超过了。要用multidex

**Comment by Symous** [comment]
是的，楼上说的没错，已采用下面的方法解决：
http://blog.csdn.net/sayid_des/article/details/50462261

谢谢！
