### ISSUE TITLE
Splash screen always appears stretched/distorted

### ISSUE THREAD

**Issue by jskidd3** [crazycodeboy/react-native-splash-screen#173]
I am trying to create a splash screen with no distortion. Every time I have used this plugin the splash screen is stretched to fill the display even when using the correct sizes. Please can someone help me understand why this is happening. I have made use of all of the drawable folders and created a bespoke sized splash screen for each display. The dimensions used were the same as listed [here](https://github.com/phonegap/phonegap/wiki/App-Splash-Screen-Sizes).

This is the original splash screen image (xxx-hdpi):

![Original image](https://i.imgur.com/HHW20f6.png)

This is how it appears on the splash screen in the app (vertical stretching):

![Stretched splash screen](https://i.imgur.com/2RTdWsG.png)

**Comment by jskidd3** [comment]
@crazycodeboy Sorry to tag you directly in this but it's quite urgent so would really appreciate your help.

**Comment by jskidd3** [comment]
Closed after finding and following guidance found here: https://github.com/crazycodeboy/react-native-splash-screen/issues/70. This really should be documented, many many hours of hair pulling could have been avoided.

**Comment by indrawanadjie** [comment]
@jskidd3 how to add bottom image like you?

**Comment by ChrystianMelo** [comment]
Im having the same problem you had....did you manage to solve your problem?

**Comment by felipebutcher** [comment]
> Im having the same problem you had....did you manage to solve your problem?

Have you read the comments? He pointed out the solution.
