### ISSUE TITLE
SplashScreen.hide() failed on Android when quit app by back button and launch again

### ISSUE THREAD

**Issue by kevinho** [crazycodeboy/react-native-splash-screen#181]
# to reproduce
1. launch app, splash show, hide as normal
2. press back button and back to home screen(the app is not kill, it's in backstack)
3. launch app again, show, hide is call, but splash still exist

**Comment by kevinho** [comment]
i figure out finally. it's not related to this library. it's the problem of life cycle of my app.

**Comment by bazambazi** [comment]
hi @kevinho 
i have this problem too
how you solved this ?

**Comment by kevinho** [comment]
@bazambazi i add listener changes of the appstate,
```
 AppState.addEventListener("change", (state)=>{
//when app become active from background, i call the SplashScreen.hide().
});
```

**Comment by bazambazi** [comment]
tnx @kevinho 
this solution fixed my problem

**Comment by kevinho** [comment]
cheers

**Comment by kevinho** [comment]
cheers

**Comment by musicode** [comment]
@kevinho do you use 'react-navigation'?

**Comment by kevinho** [comment]
@musicode yes

**Comment by musicode** [comment]
```js
AppState.addEventListener(
  'change',
  function (state) {
    if (state === 'active') {
      SplashScreen.hide()
    }
  }
)
```

a blank screen is shown....

**Comment by musicode** [comment]
my version is below
"react-navigation": "^1.5.6",
"react-native-splash-screen": "^3.0.6",

**Comment by musicode** [comment]
@kevinho what's your version?
