### ISSUE TITLE
iOS SplashScreen.h file not found

### ISSUE THREAD

**Issue by junshengpierre** [crazycodeboy/react-native-splash-screen#19]
Hi,

Thank you for the awesome library. With react-native 0.40, after running `react-native link react-native-splash-screen` and adding `#import "SplashScreen.h"` to `AppDelegate.m` for iOS, I get the error `SplashScreen.h file is not found` when trying to build the project.

Is anybody else experiencing the same issue or know what's wrong?

**Comment by mohit-pandey** [comment]
I am facing the same issue. Is there any fix?

**Comment by karolkornecki** [comment]
I also have the same problem.

**Comment by ivanperalta** [comment]
Same problem for me, Android's working but for iOs the build is broken

**Comment by yelkamel** [comment]
I got stock on the first screen "Powered by React Native"  when I add  "[SplashScreen show];" in AppDelegate.m 
I guess it's due to that.

**Comment by junshengpierre** [comment]
Haven't tried it yet but I think this is fixed in V2.0.0.

**Comment by beaurushton** [comment]
For anyone else that got stuck on this, make sure you do step 4 of the manual installation, even if you do the automatic installation with `react-native link`.

`To fix 'SplashScreen.h' file not found, you have to select your project → Build Settings → Search Paths → Header Search Paths to add:

$(SRCROOT)/../node_modules/react-native-splash-screen/ios`

**Comment by OpakAlex** [comment]
@junshengpierre doesn't works for me. I did all steps ;)

**Comment by OpakAlex** [comment]
Fixed

**Comment by grundmanise** [comment]
@beaurushton solution fixed it. Thanks

**Comment by pushpendra65** [comment]
@OpakAlex  I am also getting the error and I followed all steps.
Can you please help me, how did you solve?

**Comment by gamingumar** [comment]
change from SplashScreen.h to RNSplashScreen.h and also change in the file.
line 52 to [RNSplashScreen show];

**Comment by nkuebler000** [comment]
Add to Header Search Paths: "$(SRCROOT)/../node_modules/react-native-splash-screen/ios"
In AppDelegate.m:
#import "RNSplashScreen.h"

and

[RNSplashScreen show];

right before "return YES;"

**Comment by resting** [comment]
I get `ld: warning: directory not found for option '-L/Users/.../Library/Developer/Xcode/DerivedData/msqapp-cicwbiiflhatszcxvkwjemntqxfa/Build/Products/Debug-iphonesimulator/React' after adding the Header Search Path.

This is my current `Header Search Paths`:
![image](https://user-images.githubusercontent.com/350530/47148095-5dafd580-d302-11e8-8037-78fec16e6620.png)

**Comment by davebro** [comment]
Changing from SplashScreen to RNSplashScreen works, is that located anywhere in the docs currently?

**Comment by JOSEPHNYAMU** [comment]
Try `pod install` after `react-native link react-native-splash-screen`

**Comment by dantesolis** [comment]
Was having the problem, but I didn't have to add the `Header Search Path ....`, just changed

```swift
#import "SplashScreen.h" => #import "RNSplashScreen.h"

[SplashScreen show]; =>   [RNSplashScreen show];
```

And that fixed my problem.

Running:

```
    "react": "16.3.1",
    "react-native": "^0.55.4",
"react-native-splash-screen": "^3.0.9"
```

**Comment by ldco2016** [comment]
I tried the above fix and got this error:

```
 warning: extra tokens at end of #import directive [-Wextra-tokens]
#import "SplashScreen.h" => #import "RNSplashScreen.h"
                         ^
                         //
/Users/danale/Projects/engage-application.mobile/ios/NFIBEngage/AppDelegate.m:17:9: fatal error: 'SplashScreen.h' file not found
#import "SplashScreen.h" => #import "RNSplashScreen.h"
        ^~~~~~~~~~~~~~~~
1 warning and 1 error generated.
```

I am running:

```
"react": "16.2.0",
"react-native": "0.53.3",
"react-native-splash-screen": "^3.0.6",
```

**Comment by ManigandanRaamanathan** [comment]
@ldco2016 did you find any other solution?

**Comment by ldco2016** [comment]
@ManigandanRaamanathan , I had to uninstall and reinstall react-native-splash-screen to get past build failure with xcode and I went from `"version": "3.2.0"` to `"version": "3.0.6"`.

**Comment by jhoanborges** [comment]
> Try `pod install` after `react-native link react-native-splash-screen`

this did the trick

**Comment by Yyutaa** [comment]
add [#import SplashScreen.h] in AppDelegate.m file.  and  pod install and react-native link react-native-splash-screen.  this did the trick

**Comment by ianhunterharold** [comment]
tried all of the above approach, still looking for solution.

**Comment by calcazar** [comment]
I'm having the same problem. It doesn't appear to be code related as I can build in the DEBUG scheme but I'll get the error if I switch it to Release

**Comment by calcazar** [comment]
I ruber ducked my self in to the answer. Make sure that when you add

#import "RNSplashScreen.h"

You don't add it below the "#if DEBUG" line

**Comment by zainali225** [comment]
change "SplashScreen" to "RNSplashScreen" and add search path works for me.
<img width="781" alt="Screenshot 2022-08-02 at 10 58 01 AM" src="https://user-images.githubusercontent.com/69518824/182302723-9ed3b797-d06a-4eae-8edf-528be9644048.png">

**Comment by zainali225** [comment]
change "SplashScreen" to "RNSplashScreen" and add search path works for me.
<img width="781" alt="Screenshot 2022-08-02 at 10 58 01 AM" src="https://user-images.githubusercontent.com/69518824/182303350-b8bdfaaf-6001-4bb6-9b5f-e68de6daee32.png">
.
