### ISSUE TITLE
This package fixes the initial white screen flicker on load for iOS but does nothing more

### ISSUE THREAD

**Issue by jeffreymendez1993** [crazycodeboy/react-native-splash-screen#196]
SplashScreen.show and hide do not do anything.  .show leads to a error on iOS and hide does not do anything either. Splash screen is not being controlled however the white screen flicker is what I needed to be solved so thank you.

**Comment by jeffreymendez1993** [comment]
using 3.0.6

**Comment by stobe1** [comment]
same thing in debug version, tho in release version it does kill splash screen and it doesnt appear at all.

**Comment by stobe1** [comment]
running 3.0.1 solves the problem for me

**Comment by rynatk** [comment]
Same issue for me, 3.0.1 also fixed it.

**Comment by DerekDavisST** [comment]
same issue. Having a white screen at debug. Using 3.1. any proper solution
