### ISSUE TITLE
版本更新后java文件变化，让我搞不定android的配置了。。，不敢乱改动java代码

### ISSUE THREAD

**Issue by chunmu** [crazycodeboy/react-native-splash-screen#2]
小哥  帮忙看看现在react-native0.34版本了，MainActivity.java已经变化好多，我对java代码不熟悉，能不能帮忙look一下。。

**Comment by crazycodeboy** [comment]
react-native0.34 的MainActivity.java更加简洁了，只保留了一个需要重写的
```
@Override
 protected String getMainComponentName() {
  return "your component name"
}
```
方法。之前的一些代码转移到了MainApplication.java中。
