### ISSUE TITLE
Build failed on Android, HELP

### ISSUE THREAD

**Issue by jaychenjun** [crazycodeboy/react-native-splash-screen#219]
FAILURE: Build failed with an exception.

* Where:
Build file '/Users/----/workspace/----/node_modules/react-native-splash-screen/android/build.gradle' line: 22

* What went wrong:
A problem occurred evaluating project ':react-native-splash-screen'.
> Could not find method implementation() for arguments [directory 'libs'] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

I followed the instruction again and again, but still build failed on Android, no problem on IOS.

**Comment by vivikenen** [comment]
same issue here. I can build the APK successfully yesterday, but it fail today without any code change. 

![splash issue](https://user-images.githubusercontent.com/11569400/40695538-faae1652-6404-11e8-980b-bc61eabbabe7.jpeg)


react native version:
```
"react": "^16.0.0-alpha.12",
"react-native": "^0.47.0",
```

In `build.gradle` under `app` folder:
```
dependencies {
    compile project(':react-native-splash-screen')
    ....
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile 'com.android.support:appcompat-v7:23.0.1'
    compile 'com.facebook.react:react-native:+'
}
```
Also, I've import the package in ``MainActivity` & `MainApplication.java` file. 


Not sure what cause this issue.  
I run the same project which I clone from gitlab, it works fine now. 
But I run the same project which I clone today, it pop up this issue.

Anyone has any idea what cause this issue?
really appreciate.

**Comment by jaychenjun** [comment]
I googled and found out this might be a problem related to gradle, and I found that in the /node_module/react-native-splash/-screen/android/build.gradle are using **implementation** instead of **compile**, implementation is a new gradle version api, and I am using gradle:2.2.3.

Should I update my gradle and give it a try? but I don't want to cause other problem from my other libs

**Comment by jaychenjun** [comment]
@vivikenen  check out android/build.gredle what is your gredle version

**Comment by Darkhorse-Fraternity** [comment]
https://stackoverflow.com/questions/45099716/error40-0-could-not-find-method-implementation-for-arguments-directory-l    try?

**Comment by jaychenjun** [comment]
I finally fixed this ! Upgrade your gradle is the silution.

**Comment by jaychenjun** [comment]
If anyone have any other errors after upgrading gradle, then try to upgrade compileSdkVersion& buildToolsVersion in android/app/build.gradle

**Comment by meghnakatkamwar** [comment]
please resolve this as soon as possible

**Comment by jaychenjun** [comment]
I reopened this issue cause I realized more and more people are having this issue, I think upgrading gradle would be the best solution, although it is quite painful.

Hope this gets fixed soon.

**Comment by vikrantnegi** [comment]
I'm using gradle3.1.1 and still having this issue #220. The only solution is to change `com.android.support:appcompat-v7:27.0.2` to `com.android.support:appcompat-v7:23.0.1` and change `compiledSdkVersion` to `23`. 

Any solutions?

**Comment by jaychenjun** [comment]
@vikrantnegi 
```

// in the android/build.gradle
buildscript {
...
}

allprojects {
...
}

// add this
subprojects {
    project.configurations.all {
        resolutionStrategy.eachDependency { details ->
            if (details.requested.group == 'com.android.support'
                && !details.requested.name.contains('multidex') ) 
            {
                details.useVersion "26.1.0"
            }
        }
    }
}
```

**Comment by vivikenen** [comment]
Hi, @jaychenjun which version of gradle you upgrade to?

**Comment by vivikenen** [comment]
Fixed it, it is due to the  `com.android.support:appcompat` version.

**Comment by alihesari** [comment]
@jaychenjun Hi, My gradle version in android/build.gradle is `classpath 'com.android.tools.build:gradle:2.3.3'` But I have same problem. What version of gradle do I install?

**Comment by jaychenjun** [comment]
`classpath 'com.android.tools.build:gradle:3.1.0'`

Upgrading gradle is my solution though, you can try to upgrade `com.android.support:appcompat` first as mentioned by others above.

**Comment by alihesari** [comment]
@jaychenjun I upgraded gradle to 3.1.2 but I have error! Please see the Image. How to solve errors?!
![screen shot 1397-03-11 at 12 09 40 am](https://user-images.githubusercontent.com/8302633/40804417-701d0bba-6530-11e8-8f05-a004b3b19106.png)

**Comment by jaychenjun** [comment]
In your android/app/build.gradle
![snipaste_2018-06-01_03-46-12](https://user-images.githubusercontent.com/31823768/40804620-694fd718-654e-11e8-9a5f-3e472a48e1f7.png)

**Comment by ndreckshage** [comment]
This to be caused by `3.0.7` upgrade. If it requires gradle upgrade, it should be a major revision, not a patch

**Comment by AlirezaAkbarix** [comment]
**Syncing `gradle` versions is a very very very painful process!
Dear contributors please don't change the default `gradle/supportlibs/buildTools/...` versions! and leave them as `react-native` default version.**

**Comment by nicovak** [comment]
Ok, so i tried to repair this issue without any change to my code:

First I initiate a new project, and installed `react-native-splash-screen`

I removed locally, the changes made before https://github.com/crazycodeboy/react-native-splash-screen/commit/c078edfb93640b96ef5cda877a716cb500366a15 and the building part is looking fine with react-native default `gradle/supportlibs/buildTools/...`

Now, the app doesn't launch anymore I will keep investigating.

**Comment by nicovak** [comment]
I finally made It works, here is my conf if anyone want to test.

- I had to enable `multiDexEnabled` because I had a error on opening.
- I also had to add a piece of code because I used Onesignal

These two steps above are specific to my use case.

My `android/app/build.gradle`
```
android {
    compileSdkVersion 27
    buildToolsVersion '25.0.3'

    defaultConfig {
        applicationId "YOUR APP ID"
        minSdkVersion 16
        targetSdkVersion 27
        versionCode 12
        versionName "2.0"
        multiDexEnabled true
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
    }
```

My `android/build.gradle`
```
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.3.3'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
```

`react-native-splash-screen` build.gradle c078edf

```
apply plugin: 'com.android.library'

android {
    compileSdkVersion 25
    buildToolsVersion "25.0.3"

    defaultConfig {
        minSdkVersion 16
        targetSdkVersion 23
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:23.4.0'
    compile "com.facebook.react:react-native:+"  // From node_modules
}
```

**Comment by vivikenen** [comment]
Hi @nicovak ,
you downgrade the build gradle of the package?

**Comment by nicovak** [comment]
@vivikenen yes, I also tried https://github.com/facebook/react-native/issues/15448 and everything works fine now with last gradle's version and build tools (react-native default on are pretty old)

I also upvoted :
https://react-native.canny.io/feature-requests/p/update-android-build-tools-version-in-project-generated-by-react-native-init

**Comment by MR03web** [comment]
Upgrade gradle can fixed this,but change default setting is not a good way.

**Comment by vivikenen** [comment]
I don't know what's happen....
I was build successfully use the solution for upgrading `com.android.support:appcompat-v7:23.0.1` to 'com.android.support:appcompat-v7:27.0.2' and upgrading `compileSdkVersion 23` to `compileSdkVersion 27`. 

But suddenly, it does not work again since yesterday. 

And I try to upgrade the gradle to `distributionUrl=https\://services.gradle.org/distributions/gradle-4.4-all.zip` in `gradle-wrapper.properties` and `classpath 'com.android.tools.build:gradle:3.1.0'` in `build.gradle` under `android` folder. 

It was help me to build apk successfully, but the app crash when I try to open it, it says `The app has stoped`.

And then, I try to run on `ios`, ios does not throw any error message, but the splash image does not show when I open the app, just black screen, and then navigate to the main page.

Do you have the same issue?

**Comment by MR03web** [comment]
```
    compileSdkVersion 27
    buildToolsVersion "27.0.3"

    defaultConfig {
        minSdkVersion 16
        targetSdkVersion 23
        ...
    }
```

@vivikenen,  try upgrading buildToolsVersion,  minSdkVersion and targetSdkVersion?

**Comment by vivikenen** [comment]
Hi @MR03web  ,
Thx for your help, but I try the to upgrading the  buildToolsVersion, minSdkVersion and targetSdkVersion.
Doesn't work as well. 
It can be built successfully, but crash when I try to open it. (No code change)

**Comment by MR03web** [comment]
@vivikenen,

I created a demo only used react-native-splash-screen. It can be built successfully and running on my phone,if still can't succeed. you may need to check the android sdk environment or change a phone... 

https://github.com/MR03web/splashDemo

**Comment by aqnaruto** [comment]
same issue

**Comment by wkl007** [comment]
@MR03web thank you very much!!!

**Comment by vivikenen** [comment]
@MR03web  thx for your kind help
I've looked at the config of your demo project, it's almost same, especially those gradle & apk version. 
But not work on me
I try to change different phone & delete the build file under the android folder, not working


Also, I try to clone your demo project to build, but it says `bash: ./gradlew: Permission denied`
I try the solution online `./gradlew clean`, `./gradlew build, it says `bash: ./gradlew: No such file or directory`
Do I miss anything?

**Comment by vivikenen** [comment]
@rvasoya do you change the file inside the `/node_modules/react-native-splash-screen` ?

**Comment by aqnaruto** [comment]
@vivikenen you got into a wrong way, did you developed under windows?

**Comment by MR03web** [comment]
@vivikenen,

in the project folder and run 'react-native run-android'.
if you want to build the release APK, look this:
https://facebook.github.io/react-native/docs/signed-apk-android.html

**Comment by vivikenen** [comment]
@aqnaruto  nope, under mac

**Comment by vivikenen** [comment]
@MR03web  
yeap, I did the sign apk process, I can generate the key store, but shows `bash: ./gradlew: Permission denied`

**Comment by aqnaruto** [comment]
@vivikenen using sudo or chmod

**Comment by aqnaruto** [comment]
@rvasoya  i try it but, still not work 

![qq 20180607173038](https://user-images.githubusercontent.com/9067159/41091170-89a7ad90-6a78-11e8-81b5-2bf9e27aea34.png)

**Comment by aqnaruto** [comment]
@vivikenen  finally ，i build successfully ,i changled all my  buildToolsVersion  into  "25.0.3" ,and upgrade my grade 。and changed all my other lib such ass react-native-sound
and now
my app is  crash , when i start it .same with you . @vivikenen

**Comment by aqnaruto** [comment]
ok ok, struggled hour and hour,
i got the best solution

> android
 {
    compileSdkVersion 23
    buildToolsVersion "23.0.1"

    defaultConfig {
        minSdkVersion 16
        targetSdkVersion 23
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.android.support:appcompat-v7:23.0.1'
    compile "com.facebook.react:react-native:+"  // From node_modules
}

**Comment by andreleon** [comment]
I downgraded to `react-native-splash-screen@3.0.6` and followed this comment https://github.com/crazycodeboy/react-native-splash-screen/issues/191#issuecomment-379581833

Now it works fine 👍

**Comment by wkl007** [comment]
@aqnaruto Sorry,it doesn't work for me.Place show some demo for us.Thank you very much!!!

**Comment by aqnaruto** [comment]
@wkl007 
don't change anything except /react-native-splash-screen/build.gradle

modify those
![qq 20180608141114](https://user-images.githubusercontent.com/9067159/41141844-142247ac-6b26-11e8-9175-38f0830fa018.png)

**Comment by Jeijie** [comment]
@Léon Smit,thanks,downgraded version is the solution.
![image](https://user-images.githubusercontent.com/9338052/41146380-b07f39e8-6b35-11e8-819b-7afff83db363.png)

**Comment by vivikenen** [comment]
I saw the package has downgraded back to 23. 
Does it work for you guys?

I got new bug..... 
I did not change anything, expect the gradle & compile sdk version to 23
![splashactivity](https://user-images.githubusercontent.com/11569400/41524559-4e16214c-7321-11e8-8742-f3278551a78d.jpeg)

**Comment by shakedOno** [comment]
As of version 3.0.9 this does not happen anymore

**Comment by zmGitHub** [comment]
1. edit android/build/gradle add:
```
ext {
    buildToolsVersion = "26.0.3"
    minSdkVersion = 16
    compileSdkVersion = 26
    targetSdkVersion = 26
    supportLibVersion = "26.1.0"
}
2. and /android/app/build.grade
![image](https://user-images.githubusercontent.com/6838405/43882966-28dfd6c0-9be4-11e8-9680-7fbe61623372.png)

3. 
```
allprojects {
    repositories {
        mavenLocal()
        jcenter()
       // add this
        maven {
            url 'https://maven.google.com'
        }
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
    }
}
```

**Comment by Tom29** [comment]
Failed to build on android

```
apply plugin: 'com.android.library'

android {
    compileSdkVersion 26
    buildToolsVersion '27.0.3'

    defaultConfig {
        minSdkVersion 16
        targetSdkVersion 26
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    testImplementation 'junit:junit:4.12'
    implementation 'com.android.support:appcompat-v7:26.1.0'
    implementation "com.facebook.react:react-native:+" // From node_modules
}

```

`Failed to resolve: support-v4`

**Comment by ThiruRJST** [comment]
yeah I too get the same issue in gradle 4.0.2
