### ISSUE TITLE
com.android.support:appcompat-v7' dependency issue 

### ISSUE THREAD

**Issue by vikrantnegi** [crazycodeboy/react-native-splash-screen#220]
**Versions**:
react-native: 0.55.2
react-native-splash-screen: 3.0.7

I was facing this issue when trying to run `react-native run-android`.
```
Android dependency 'com.android.support:appcompat-v7' has different version for the compile react native splash screen
```

I'm able to  solved this issue by editing `react-native-splash-screen` `build.gradle` file dependencies to the following code

```
implementation 'com.android.support:appcompat-v7:23.0.1'
```

and changing the compileSdkVersion to 23

Is there any other way to resolve this issue without modifying the gradle file?
Thanks

**Comment by jaychenjun** [comment]
#219

**Comment by vikrantnegi** [comment]
I'm using `gradle` version `3.1.1 ` and still having the issue.

**Comment by aqnaruto** [comment]
same issue , same Upgrading gradle doesn't help

**Comment by zangaibaby** [comment]
@aqnaruto 
![default](https://user-images.githubusercontent.com/39050423/41220616-894df060-6d94-11e8-8e52-e91dd4f1920d.png)
![default](https://user-images.githubusercontent.com/39050423/41220616-894df060-6d94-11e8-8e52-e91dd4f1920d.png)
![default](https://user-images.githubusercontent.com/39050423/41220616-894df060-6d94-11e8-8e52-e91dd4f1920d.png)
![default](https://user-images.githubusercontent.com/39050423/41220616-894df060-6d94-11e8-8e52-e91dd4f1920d.png)

**Comment by zangaibaby** [comment]
![default](https://user-images.githubusercontent.com/39050423/41220616-894df060-6d94-11e8-8e52-e91dd4f1920d.png)![default](https://user-images.githubusercontent.com/39050423/41220616-894df060-6d94-11e8-8e52-e91dd4f1920d.png)![default](https://user-images.githubusercontent.com/39050423/41220616-894df060-6d94-11e8-8e52-e91dd4f1920d.png)![default](https://user-images.githubusercontent.com/39050423/41220616-894df060-6d94-11e8-8e52-e91dd4f1920d.png)

**Comment by crazycodeboy** [comment]
Beginning with the [3.0.9](https://github.com/crazycodeboy/react-native-splash-screen/commit/31243df7ceaf768f3427c1ee4ead1d9fa2c5957a) version [build.gradle](https://github.com/crazycodeboy/react-native-splash-screen/blob/master/android/build.gradle) will be kept with [react-native build.gradle](https://github.com/facebook/react-native/blob/master/ReactAndroid/build.gradle).
