### ISSUE TITLE
A TypeError occurs after the document is set

### ISSUE THREAD

**Issue by ParkourH** [crazycodeboy/react-native-splash-screen#225]
<img width="381" alt="2018-06-06 6 23 03" src="https://user-images.githubusercontent.com/22805546/41032752-ee573a7a-69b6-11e8-914b-fc7c010bad22.png">
How to solve???

**Comment by thisisbalaG** [comment]
I also have the same issue.. please help 

![Screenshot_1564640279](https://user-images.githubusercontent.com/40167110/62269976-5a7d7480-b452-11e9-9d47-7171f34698bd.png)

**Comment by thisisbalaG** [comment]
@ParkourH please help to fix this issue.
