### ISSUE TITLE
Could not find runtime.aar

### ISSUE THREAD

**Issue by ebsuku** [crazycodeboy/react-native-splash-screen#228]
When try to build my project i run into this issue
```
> Could not find runtime.aar (android.arch.lifecycle:runtime:1.0.3).
  Searched in the following locations:
      https://jcenter.bintray.com/android/arch/lifecycle/runtime/1.0.3/runtime-1.0.3.aar
```
I looked on that site and there is no .aar for 1.0.3, 
Where/How can I  upgrade or downgrade the runtime version?

**Comment by LyhengTep** [comment]
@ebsuku hi bro have u find any solution with this yet ?

**Comment by ebsuku** [comment]
@LyhengTep nope,
I took a look  at the source files but I cant find a place where the version is specified.
So I've just decided to hold off on building the splash screen until the library gets updated.

**Comment by pietro909** [comment]
Any news on this one? Is breaking our build and removing the library is not an option... could we please get a working version, even an old one?

**Comment by variant77** [comment]
Seems like the current best solution is to add **_google()_** to the repositories section in _build.grade_. If it's already there then move it to the top:
```
repositories {
        google()
        jcenter()
}
```

**Comment by ebsuku** [comment]
So I started working with the splash screen today and no problems. I did not have to edit any buildscripts.

So i guess the issue can be closed?
