### ISSUE TITLE
This package not working for me

### ISSUE THREAD

**Issue by DikshaDeep** [crazycodeboy/react-native-splash-screen#229]
I am install this package using following commands

``` npm i react-native-splash-screen --save ``` and after that run following command
``` react-native link react-native-splash-screen  ```

When i run ``` react-native run-android ``` i am getting following error on terminal

![screen shot 2018-06-08 at 3 58 31 pm](https://user-images.githubusercontent.com/32561815/41153672-0aa1b1cc-6b35-11e8-82fc-63eecfd60857.png)

**Comment by noobiept** [comment]
Not working here too, any ideas?

**Comment by adrian-ponce-wolox** [comment]
I got the same bug. 😕 
I have changed the `dependencies` on `./android/build.gradle` from `implement` to `compile` and it worked. But it needs to be changed on the package to be definitive 😕 

I've used for `./android/build.gradle`:
```
apply plugin: 'com.android.library'

android {
    compileSdkVersion 27
    buildToolsVersion "27.0.3"

    defaultConfig {
        minSdkVersion 16
        targetSdkVersion 23
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:27.0.2'
    compile "com.facebook.react:react-native:+"  // From node_modules
}
```

**Comment by RobertSasak** [comment]
I found this solution. 
https://stackoverflow.com/questions/45615474/gradle-error-could-not-find-method-implementation-for-arguments-com-android

I opened *node_modules/react-native-splash-screen/android/build.gradle* and replaced *implementation* by *compile* and *testImplementation* with *testCompile*.

Here is my final *build.gradle*
```
apply plugin: 'com.android.library'

android {
    compileSdkVersion 27
    buildToolsVersion "27.0.3"

    defaultConfig {
        minSdkVersion 16
        targetSdkVersion 23
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:27.0.2'
    compile "com.facebook.react:react-native:+"  // From node_modules
}
```

**Comment by RobertSasak** [comment]
I made PR https://github.com/crazycodeboy/react-native-splash-screen/pull/231

**Comment by crazycodeboy** [comment]
Beginning with the [3.0.9](https://github.com/crazycodeboy/react-native-splash-screen/commit/31243df7ceaf768f3427c1ee4ead1d9fa2c5957a) version [build.gradle](https://github.com/crazycodeboy/react-native-splash-screen/blob/master/android/build.gradle) will be kept with [react-native build.gradle](https://github.com/facebook/react-native/blob/master/ReactAndroid/build.gradle).
