### ISSUE TITLE
建议：安卓能不能不要用button 来实现

### ISSUE THREAD

**Issue by aqnaruto** [crazycodeboy/react-native-splash-screen#240]
如果用button的话 那么你只能去用一个背景图片，这样在不同屏幕手机上容易变形。
还有，我想让顶部的statusBar消失也不行。
为什么一定要用button来实现呢
早知如此还不如自己写原生
一点也不好
不爱了
心塞
累

**Comment by aqnaruto** [comment]
不好意思，看了下代码 可以全屏。祝您身体健康 万事如意 和我一样帅

**Comment by shen-lan** [comment]
怎么全屏的？我的启动页状态栏是黑色的
已添加：
```
<item name="android:windowIsTranslucent">true</item>
```
