### ISSUE TITLE
Breaks on Android with React Native 0.56

### ISSUE THREAD

**Issue by taranda** [crazycodeboy/react-native-splash-screen#245]
After upgrading to React Native 0.56, the react-native-splash-screen package prevents `react-native run android` from running:

```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApk'.
   > A problem occurred configuring project ':react-native-splash-screen'.
      > The SDK Build Tools revision (23.0.1) is too low for project ':react-native-splash-screen'. Minimum required is 25.0.0
```

The Google Play store requires will require apps to use API 26 by August 2018, so this issue is somewhat time sensitive.

**Comment by taranda** [comment]
[PR 256](https://github.com/bugsnag/bugsnag-react-native/pull/256) may address this issue.  However, I am not an Android developer and I have not tested this PR.

The way [react-native-device-info handled this](https://github.com/rebeccahughes/react-native-device-info/blob/v0.21.5/android/build.gradle) is elegant.  It makes it backward compatible.

**Comment by Ashoat** [comment]
I was able to get around this by updating `node_modules/react-native-splash-screen/android/build.gradle` to the following:

```
apply plugin: 'com.android.library'

android {
    compileSdkVersion 26
    buildToolsVersion "26.0.2"

    defaultConfig {
        minSdkVersion 16
        targetSdkVersion 26
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:23.4.0'
    compile "com.facebook.react:react-native:+"  // From node_modules
}
```

@crazycodeboy, let me know if you'd like me to submit a PR with this change.

**Comment by taranda** [comment]
I think [PR 246](https://github.com/crazycodeboy/react-native-splash-screen/pull/246) is already addressing this.  Any solution would be welcome.

**Comment by crazycodeboy** [comment]
[v3.1.0](https://github.com/crazycodeboy/react-native-splash-screen/releases/tag/v3.1.0)
