### ISSUE TITLE
Build failed on v.3.1.0

### ISSUE THREAD

**Issue by anton-loktev** [crazycodeboy/react-native-splash-screen#250]
In new release there is a bug.
You forget to rename 
[SplashScreen show];
to RNSplashScreen in RNSplashScreen.m

And also in documentation for install i think you should update AppDelegate.m with rename #import "SplashScreen.h" to "RNSplashScreen.h"
Thanks.

**Comment by kirillpisarev** [comment]
@crazycodeboy #251 i just created pr that fixes this issue

**Comment by jacargentina** [comment]
Just updated, same error here.

**Comment by brenwell** [comment]
Worked for me

**Comment by jackgreen04** [comment]
Hello mate, 

I tried to change it the way you said so but still RNSplashScreen show never gets trigger. and on xccode it says the following
`/**
 * Copyright (c) 2015-present, Facebook, Inc.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

#import "AppDelegate.h"

#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>
#import "RNSplashScreen.h"

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  NSURL *jsCodeLocation;

  jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];

  RCTRootView *rootView = [[RCTRootView alloc] initWithBundleURL:jsCodeLocation
                                                      moduleName:@"SayaraApp"
                                               initialProperties:nil
                                                   launchOptions:launchOptions];
  rootView.backgroundColor = [[UIColor alloc] initWithRed:1.0f green:1.0f blue:1.0f alpha:1];

  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [UIViewController new];
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];
  return YES;

  [RNSplashScreen show]; code will never be executed
  return YES;
}

@end
`

**Comment by gabrielbull** [comment]
@jackgreen04 Take a look here:

```objective-c
return YES;

[RNSplashScreen show]; code will never be executed
return YES;
```

You `return YES` before executing `[RNSplashScreen show]`.

**Comment by jackgreen04** [comment]
Hello @gabrielbull. I think if you go back to my snippet before calling RNSplashScreen i alredy return yes.

**Comment by gabrielbull** [comment]
@jackgreen04 Exactly, any code after a return statement will never be executed.

**Comment by jackgreen04** [comment]
I see mate thank you. I will try it later.
