### ISSUE TITLE
Do not upgrade

### ISSUE THREAD

**Issue by aniwei** [crazycodeboy/react-native-splash-screen#256]
RCT_EXPORT_METHOD(show) {
    [SplashScreen show]; 
    //  [RNSplashScreen show];
}

brother，your code has bug。

**Comment by mtt87** [comment]
`3.0.9` is the latest working version
`3.1.0` is broken as stated above

**Comment by StevenMasini** [comment]
Yes I just noticed this. It's easy to fix though, I was going to submit a PR. 

Do you want me to submit the PR ?

**Comment by StevenMasini** [comment]
There is actually plenty of fix for this issue waiting in the PR queue.

**Comment by victorhugoweb** [comment]
@crazycodeboy  are you doing with this project?
a lot of mistakes

**Comment by StevenMasini** [comment]
@amos80m I am not from the `react-native-splash-screen` community but this [pull request](https://github.com/crazycodeboy/react-native-splash-screen) fix the issue.

So you can replace the path to `react-native-splash-screen` in your `package.json` to 
```
"react-native-splash-screen": "kirillpisarev/react-native-splash-screen#0c4fb119774fe9e812e5061fd4fb55989393b4d8"
```

Or you can also just simply use `3.0.9` which is stable.
