### ISSUE TITLE
'SplashScreen.h' file not found

### ISSUE THREAD

**Issue by ratkus91** [crazycodeboy/react-native-splash-screen#257]
version: **3.1.0**
You probably have not rebuilt the file: **libSplashScreen.a**

_The module is not working_

**Comment by pycarlos** [comment]
They are changed the name of file now RNSplashSreen.h

**Comment by gamsim** [comment]
The readme file is out of date. As per pycarlos.

**Comment by pycarlos** [comment]
Yes, Readme in version 3.0.9 is good. 
I just created an app then test it and is working.

**Comment by missRuoHua** [comment]
use SplashScreen.h, change RNSplashScreen.m #53 SplashScreen to RNSplashScreen,it working!

**Comment by PakpahanLeo** [comment]
> 
> 
> They are changed the name of file now RNSplashSreen.h

@lcmartinezdev  cool bro
