### ISSUE TITLE
iOS Build failed: unknown receiver 'SplashScreen'; did you mean 'RNSplashScreen'

### ISSUE THREAD

**Issue by ngouass** [crazycodeboy/react-native-splash-screen#260]
Hi, I'm facing the following issue on version 3.1.0 with Xcode 9 while building iOS app
```
node_modules/react-native-splash-screen/ios/RNSplashScreen.m:52:6: unknown receiver 'SplashScreen'; did you mean 'RNSplashScreen'?
```

Looking at **RNSplashScreen.m:52:6**, I found this
```
RCT_EXPORT_METHOD(show) {
    [SplashScreen show];
}
```
When replacing **SplashScreen** by **RNSplashScreen** the build succeeds. But I'm wondering if it's the right way to go.

Thanks.

**Comment by flyinghawker** [comment]
+1

**Comment by ebaynaud** [comment]
Please publish a 3.1.0 with this change!!

**Comment by CptFabulouso** [comment]
I think it should be replaced, I also had to rename it in `AppDelegate.m`. 
If so, documentation should be also updated to `#import "RNSplashScreen.h"` and `[RNSplashScreen show];`

**Comment by ngouass** [comment]
@CptFabulouso there is already a pull request for updating the installation documentation for iOS https://github.com/crazycodeboy/react-native-splash-screen/pull/254/commits/efd49072a9756cf84d7876bf8f13867ae3ffe529

**Comment by CptFabulouso** [comment]
I see, also the export has PR #253

**Comment by jjzazuet** [comment]
+1 :(...

**Comment by wowzaaa** [comment]
+1

**Comment by xcv58** [comment]
+1

**Comment by fkrauthan** [comment]
Any news on this ticket? Currently the plugin is broken unfortunately.
