### ISSUE TITLE
[iOS] Cannot archive for app store: Invalid Symlink

### ISSUE THREAD

**Issue by neilhamilton** [crazycodeboy/react-native-splash-screen#262]
Getting error:

`Your package contains a symbolic link 'react-native-splash-screen/node_modules/.bin/react-native' which resolves to a location 'react-native-splash-screen/node_modules/.bin/../../../react-native/local-cli/wrong-react-native.js' that does not exist or is outside of the package.`

React Native: v0.55.1
react-native-splash-screen: v3.0.9

I have gone through the manual steps to install and see all of the correct files/Header Search Paths in xCode. Not sure what else I can check.

I have also tried installing React Native locally (as it says to in `react-native-splash-screen/node_modules/.bin/react-native`

Release build for simulator works fine with no errors.

Any help would be greatly appreciated!

**Comment by neilhamilton** [comment]
Was able to solve this with:

unlink node_modules/react-native-splash-screen/node_modules/.bin/react-native

**Comment by rogueturnip** [comment]
I got this back from my submission but when I unlink it says file not found.  Any suggestions?

Should cocoapods be used?

**Comment by neilhamilton** [comment]
@rogueturnip can you post the output from AppStore Connect?

**Comment by AshtonKem** [comment]
@rogueturnip Could you explain a bit more please? I'm seeing the same issue for a different library, tipsi-stripe.

**Comment by rogueturnip** [comment]
@ashtonkem I found that using link and cocoapods had conflicting libraries.  I removed everything and did everything over and it seemed to clean things up.

**Comment by bernatbombi** [comment]
The error still exists.

We have completely removed the library and installed it again, with the same result. 

The App Store Connect message is:

ITMS-90332: Invalid Symbolic Link - The symbolic link 'react-native-splash-screen/node_modules/.bin/react-native' resolves to an invalid location. Make sure that the symbolic link does not resolve to itself, and that the location exists and is contained within the app bundle.
