### ISSUE TITLE
Could not show splash screen again on iOS.

### ISSUE THREAD

**Issue by PMExtra** [crazycodeboy/react-native-splash-screen#268]
My application have a function that need to "reload js".
So I want to use "react-native-restart" with "react-native-splash-screen".
They work fine on Android.
But I found that it would not show splash screen when I call `SplashScreen.show()` from js on iOS.
I have looked the native code for iOS, it's just a waiter in `show()`, it's very different from Android.

It that any solution for my requirement?
Whatever, I think it should be explained in README, it cost me a lot of time.

**Comment by PMExtra** [comment]
哇，才发现这个项目是国人写的。早知道直接说中文了。
感觉应该是有办法在运行时拿到LaunchImage或者LaunchScreen的。
参考：
https://stackoverflow.com/questions/25966865/programmatically-accessing-the-launch-screen-xib-or-storyboard
http://adad184.com/2015/10/15/tips-access-current-launch-image

**Comment by binhnd-socicom** [comment]
I think you can refer my PR to get your solution you need. I'm using launch-screen similar to what you mentioned above.
https://github.com/crazycodeboy/react-native-splash-screen/pull/234

**Comment by PMExtra** [comment]
@binhnd-socicom Great! That's what I want. But I think it would be better if it keep the design consistent with android (remove the looping wait, use the over view default, and just overload the `show` method).
**In the end, the most important thing is that, I need to use LaunchImage instead xib/storyboard.**

**Comment by hpmax00** [comment]
@PMExtra 
You can try this , but it may be slow in android. Or I can fix the android problem later.
react-native-splashscreen

**Comment by PMExtra** [comment]
@hpmax00 I'm not sure what your mean. I have used it on Android, it works fine.

**Comment by kodie** [comment]
Being able to call `SplashScreen.show()` should really be implemented
