### ISSUE TITLE
error after completing the official documentation configuration.  A problem occurred configuring project ':react-native-splash-screen'.

### ISSUE THREAD

**Issue by Mar-er** [crazycodeboy/react-native-splash-screen#274]
* What went wrong:
A problem occurred configuring project ':app'.
> A problem occurred configuring project ':react-native-splash-screen'.
   > Could not resolve all dependencies for configuration ':react-native-splash-screen:_debugCompile'.
      > Could not find com.android.support:appcompat-v7:26.1.0.
        Searched in the following locations:
            file:/C:/Users/cj-wj/.m2/repository/com/android/support/appcompat-v7/26.1.0/appcompat-v7-26.1.0.pom
            file:/C:/Users/cj-wj/.m2/repository/com/android/support/appcompat-v7/26.1.0/appcompat-v7-26.1.0.jar
            https://jcenter.bintray.com/com/android/support/appcompat-v7/26.1.0/appcompat-v7-26.1.0.pom
            https://jcenter.bintray.com/com/android/support/appcompat-v7/26.1.0/appcompat-v7-26.1.0.jar
            file:/C:/Document/Code/CJKJ/cjhms_rn/node_modules/react-native/android/com/android/support/appcompat-v7/26.1.0/appcompat-v7-26.1.0.pom
            file:/C:/Document/Code/CJKJ/cjhms_rn/node_modules/react-native/android/com/android/support/appcompat-v7/26.1.0/appcompat-v7-26.1.0.jar
            file:/C:/Users/cj-wj/AppData/Local/Android/Sdk/extras/android/m2repository/com/android/support/appcompat-v7/26.1.0/appcompat-v7-26.1.0.pom
            file:/C:/Users/cj-wj/AppData/Local/Android/Sdk/extras/android/m2repository/com/android/support/appcompat-v7/26.1.0/appcompat-v7-26.1.0.jar
            file:/C:/Users/cj-wj/AppData/Local/Android/Sdk/extras/google/m2repository/com/android/support/appcompat-v7/26.1.0/appcompat-v7-26.1.0.pom
            file:/C:/Users/cj-wj/AppData/Local/Android/Sdk/extras/google/m2repository/com/android/support/appcompat-v7/26.1.0/appcompat-v7-26.1.0.jar
        Required by:
            cjhms_rn:react-native-splash-screen:unspecified
      > Could not find com.android.support:appcompat-v7:26.1.0.
        Searched in the following locations:
            file:/C:/Users/cj-wj/.m2/repository/com/android/support/appcompat-v7/26.1.0/appcompat-v7-26.1.0.pom
            file:/C:/Users/cj-wj/.m2/repository/com/android/support/appcompat-v7/26.1.0/appcompat-v7-26.1.0.jar
            https://jcenter.bintray.com/com/android/support/appcompat-v7/26.1.0/appcompat-v7-26.1.0.pom
            https://jcenter.bintray.com/com/android/support/appcompat-v7/26.1.0/appcompat-v7-26.1.0.jar
            file:/C:/Document/Code/CJKJ/cjhms_rn/node_modules/react-native/android/com/android/support/appcompat-v7/26.1.0/appcompat-v7-26.1.0.pom
            file:/C:/Document/Code/CJKJ/cjhms_rn/node_modules/react-native/android/com/android/support/appcompat-v7/26.1.0/appcompat-v7-26.1.0.jar
            file:/C:/Users/cj-wj/AppData/Local/Android/Sdk/extras/android/m2repository/com/android/support/appcompat-v7/26.1.0/appcompat-v7-26.1.0.pom
            file:/C:/Users/cj-wj/AppData/Local/Android/Sdk/extras/android/m2repository/com/android/support/appcompat-v7/26.1.0/appcompat-v7-26.1.0.jar
            file:/C:/Users/cj-wj/AppData/Local/Android/Sdk/extras/google/m2repository/com/android/support/appcompat-v7/26.1.0/appcompat-v7-26.1.0.pom
            file:/C:/Users/cj-wj/AppData/Local/Android/Sdk/extras/google/m2repository/com/android/support/appcompat-v7/26.1.0/appcompat-v7-26.1.0.jar
        Required by:
            cjhms_rn:react-native-splash-screen:unspecified > com.facebook.react:react-native:0.55.4

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**Comment by caobing** [comment]
简单方法降到3.0.9需要注意，在dependencies{
"react-native-splash-screen": "3.0.9",  //不能有^，复制会自动升级
}
另外就是修改node_modules\react-native-splash-screen\android\build.gradle
为
compileSdkVersion 23
buildToolsVersion "23.0.1"
targetSdkVersion 22
compile 'com.android.support:appcompat-v7:23.0.1'

**Comment by BadMaker** [comment]
@caobing thanks,it's work
