### ISSUE TITLE
Android app crashes on open

### ISSUE THREAD

**Issue by radjivF** [crazycodeboy/react-native-splash-screen#284]
i got this error: 

```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApk'.
   > A problem occurred configuring project ':react-native-splash-screen'.
      > Could not resolve all dependencies for configuration ':react-native-splash-screen:_debugPublishCopy'.
         > Could not find com.android.support:appcompat-v7:26.1.0.
```

Any idea, what I could have done wrong?

**Comment by VahidBo** [comment]
My app crashes at start, When I run my app on the android devices that use android 8. I got the full error log and I found the following error:

`AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{myAppPackage/myAppPackage.MainActivity}: java.lang.IllegalStateException: Only fullscreen opaque activities can request orientation`

This error is because of setting android orientation.
And I test my app on a android device with android version 6 and my app works properly.

**Comment by VahidBo** [comment]
My app crashes at start, When I run my app on the android devices that use android 8. I got the full error log and I found the following error:

```
AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{myAppPackage/myAppPackage.MainActivity}: java.lang.IllegalStateException: Only fullscreen opaque activities can request orientation
```

This error is because of setting android orientation.
And I test my app on a android device with android version 6 and my app works properly.

**Comment by nilaybrahmbhatt** [comment]
@wachidyulio  but whats the solution for 26.0.1 ? having same problem.

**Comment by WilliamAlexander** [comment]
Do not change the compileSdkVersion to 23.
Google are beginning to only accept apk files that are >=26

**Comment by thongnx6** [comment]
@idtechnology hope that you can see something at here https://medium.com/handlebar-labs/how-to-add-a-splash-screen-to-a-react-native-app-ios-and-android-30a3cec835ae

**Comment by Riant** [comment]
@VahidBo I removed the style line 
```<item name="android:windowIsTranslucent">true</item>```
then it wokrs fine on Android 8.0

**Comment by mepritam** [comment]
On your **android/app/src/main/res/values/colors.xml** add this line
`<color name="primary_dark">#4F6D7A</color>`

This line **solved my app crash after open problem**.

This is my full colors.xml code 
`<?xml version="1.0" encoding="utf-8"?>`
`<resources>`
    `<color name="blue">#4F6D7A</color>`
    `<color name="primary_dark">#4F6D7A</color>`
`</resources>
`


Try this it may works for you  😄 👍

**Comment by radjivF** [comment]
thx guys I think we can close it now

**Comment by thaitd96** [comment]
> @VahidBo I removed the style line
> `<item name="android:windowIsTranslucent">true</item>`
> then it wokrs fine on Android 8.0

Thank bro, this worked for me <3

**Comment by Zeta-DangTam** [comment]
> @VahidBo I removed the style line `<item name="android:windowIsTranslucent">true</item>` then it wokrs fine on Android 8.0

thanks bro. this worked for me
