### ISSUE TITLE
Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'

### ISSUE THREAD

**Issue by mnlbox** [crazycodeboy/react-native-splash-screen#311]
Hi @crazycodeboy I see this warning in new app:
```
> Configure project :react-native-splash-screen 
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
WARNING: Configuration 'testCompile' is obsolete and has been replaced with 'testImplementation' and 'testApi'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
WARNING: Configuration 'testApi' is obsolete and has been replaced with 'testImplementation'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
WARNING: The specified Android SDK Build Tools version (26.0.3) is ignored, as it is below the minimum supported version (27.0.3) for Android Gradle Plugin 3.1.4.
Android SDK Build Tools 27.0.3 will be used.
To suppress this warning, remove "buildToolsVersion '26.0.3'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.
```

I think it's related to gradle version and we need some update to fix this.

**Comment by Shhzdmrz** [comment]
+1

**Comment by rajnishcoder** [comment]
any update ?

**Comment by ozalexo** [comment]
> How to Avoid this issue

Please find my workaround here: https://github.com/ozalexo/ChronoMint-RN/blob/209e5e9a23ef6e6a237df6cd4c42658d8b3d6f71/docs/PATCHPACKAGE.md

**Comment by amnan181** [comment]
hi i can remove this error....
Sorry for poor english...!
change all **bundle.gradle** files
goto your project and then **node_modules** then goto where module you installed ex**.react-native-splash-screen**.Find and open build.gradle ----->> buildToolsVersion : "27.0.3"
and next find dependencies change where write compile and then change **compile** to "implementation".
if you are face any problem then you paste your comment.

**Comment by CONSJOBS** [comment]
There is no compile, all are implementation, what is this error?

**Comment by AftabUfaq** [comment]
i have warning in the react-native-fetch-blob library ......
Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'. It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html WARNING: Configuration 'testCompile' is obsolete and has been replaced with 'testImplementation' and 'testApi'. It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html WARNING: Configuration 'testApi' is obsolete and has been replaced with 'testImplementation'. It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html WARNING: The specified Android SDK Build Tools version (26.0.3) is ignored, as it is below the minimum supported version (27.0.3) for Android Gradle Plugin 3.1.4. Android SDK Build Tools 27.0.3 will be used. To suppress this warning, remove "buildToolsVersion '26.0.3'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.

**Comment by 1-pro** [comment]
I have been battling with same error

yarn run:android
yarn run v1.22.17
warning ../../package.json: No license field
$ react-native run-android
info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 1673 file(s) to forward-jetify. Using 4 workers...
info Starting JS server...
* daemon not running; starting now at tcp:5037
* daemon started successfully
info Launching emulator...
info Successfully launched emulator.
info Installing the app...
Starting a Gradle Daemon, 1 busy Daemon could not be reused, use --status for details

> Configure project :app
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:preDebugBuild'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve androidx.multidex:multidex:2.0.0.
     Required by:
         project :app
      > Could not resolve androidx.multidex:multidex:2.0.0.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/androidx/multidex/multidex/2.0.0/multidex-2.0.0.pom'.
            > Could not GET 'https://dl.google.com/dl/android/maven2/androidx/multidex/multidex/2.0.0/multidex-2.0.0.pom'.
               > Remote host terminated the handshake
      > Skipped due to earlier error
   > Could not resolve androidx.multidex:multidex:2.0.0.
     Required by:
         project :app
      > Could not resolve androidx.multidex:multidex:2.0.0.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/androidx/multidex/multidex/2.0.0/multidex-2.0.0.pom'.
            > Could not GET 'https://dl.google.com/dl/android/maven2/androidx/multidex/multidex/2.0.0/multidex-2.0.0.pom'.
               > Remote host terminated the handshake
      > Skipped due to earlier error
   > Could not resolve com.facebook.react:react-native:+.
     Required by:
         project :app
         project :app > project :react-native-community_masked-view
         project :app > project :react-native-community_toolbar-android
         project :app > project :react-native-gesture-handler
         project :app > project :react-native-localize
         project :app > project :react-native-reanimated
         project :app > project :react-native-safe-area-context
         project :app > project :react-native-screens
         project :app > project :react-native-vector-icons
      > Failed to list versions for com.facebook.react:react-native.
         > Unable to load Maven meta-data from https://dl.google.com/dl/android/maven2/com/facebook/react/react-native/maven-metadata.xml.
            > Could not get resource 'https://dl.google.com/dl/android/maven2/com/facebook/react/react-native/maven-metadata.xml'.
               > Could not GET 'https://dl.google.com/dl/android/maven2/com/facebook/react/react-native/maven-metadata.xml'.
                  > dl.google.com: Temporary failure in name resolution
      > Failed to list versions for com.facebook.react:react-native.
         > Unable to load Maven meta-data from https://jcenter.bintray.com/com/facebook/react/react-native/maven-metadata.xml.
            > Could not get resource 'https://jcenter.bintray.com/com/facebook/react/react-native/maven-metadata.xml'.
               > Could not GET 'https://jcenter.bintray.com/com/facebook/react/react-native/maven-metadata.xml'.
                  > Connect to jcenter.bintray.com:443 [jcenter.bintray.com/34.95.74.180] failed: connect timed out
   > Could not resolve androidx.swiperefreshlayout:swiperefreshlayout:1.0.0.
     Required by:
         project :app > project :react-native-screens
      > Could not resolve androidx.swiperefreshlayout:swiperefreshlayout:1.0.0.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/androidx/swiperefreshlayout/swiperefreshlayout/1.0.0/swiperefreshlayout-1.0.0.pom'.
            > Could not GET 'https://dl.google.com/dl/android/maven2/androidx/swiperefreshlayout/swiperefreshlayout/1.0.0/swiperefreshlayout-1.0.0.pom'.
               > dl.google.com: Temporary failure in name resolution
      > Skipped due to earlier error

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 9m 24s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup. Run CLI with --verbose flag for more details.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Please whats the solution?

**Comment by aaryavrate** [comment]
Why some "Genius" does this type of name change? sucks :(

**Comment by sharjeel125** [comment]
Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed soon. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
Affected Modules: PDFView, app, react-native-pdf-view

**Comment by sharjeel125** [comment]
Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed soon. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
Affected Modules: PDFView, app, react-native-pdf-view 
 please help how to get rid of this  ..... this throw error  pdf view is affected and throws error not able to build how to fix this 



Could not determine the dependencies of task ':PDFView:compileDebugRenderscript'.
> Could not resolve all task dependencies for configuration ':PDFView:debugCompileClasspath'.
   > Could not resolve com.facebook.react:react-native:0.20.+.
     Required by:
         project :PDFView
      > Failed to list versions for com.facebook.react:react-native.
         > Unable to load Maven meta-data from https://jcenter.bintray.com/com/facebook/react/react-native/maven-metadata.xml.
            > Could not HEAD 'https://jcenter.bintray.com/com/facebook/react/react-native/maven-metadata.xml'.
               > org.apache.http.client.ClientProtocolException (no error message)
      > Failed to list versions for com.facebook.react:react-native.
         > Unable to load Maven meta-data from https://jcenter.bintray.com/com/facebook/react/react-native/maven-metadata.xml.
            > Could not HEAD 'https://jcenter.bintray.com/com/facebook/react/react-native/maven-metadata.xml'.
               > org.apache.http.client.ClientProtocolException (no error message)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
