### ISSUE TITLE
RN 0.57.2 Android MainActivity.java - How to configure?

### ISSUE THREAD

**Issue by tuomohopia** [crazycodeboy/react-native-splash-screen#317]
In 0.57.2 my Android's `MainActivity.java` looks like the following:

```java
package com.packagename;

import com.facebook.react.ReactActivity;

public class MainActivity extends ReactActivity {

    /**
     * Returns the name of the main component registered from JavaScript.
     * This is used to schedule rendering of the component.
     */
    @Override
    protected String getMainComponentName() {
        return "packagename";
    }
}
```

**How to configure this file to use `react-native-splash-screen` as it has no onCreate method in it?**

**Comment by xkdaq** [comment]
重写onCreated方法呀,这个方法是Activity的创建的方法 ,然后加上SplashScreen.show(this); 就行了
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        SplashScreen.show(this);  // here
        super.onCreate(savedInstanceState);
    }

**Comment by tuomohopia** [comment]
Thanks, got it to work!

**Comment by devsarosh** [comment]
How it worked ? Please brief it once...

**Comment by bailihuiyue** [comment]
重写onCreate方法了,但是报错
错误: 找不到符号:
app:compileDebugJavaWithJavac
    protected void onCreate(Bundle savedInstanceState) {
                            ^
  符号:   类 Bundle
  位置: 类 MainActivity

**Comment by duxiaofeng-github** [comment]
@bailihuiyue 

import android.os.Bundle;
