### ISSUE TITLE
"_OBJC_CLASS_$_RNSplashScreen", referenced from:       objc-class-ref in AppDelegate.o

### ISSUE THREAD

**Issue by zuijiaoluo** [crazycodeboy/react-native-splash-screen#318]
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_RNSplashScreen", referenced from:
      objc-class-ref in AppDelegate.o

ld: symbol(s) not found for architecture x86_64

clang: error: 

linker command failed with exit code 1 (use -v to see invocation)

**Comment by Tiger-man** [comment]
@zuijiaoluo 怎么解决的

**Comment by cristianonescu** [comment]
@zuijiaoluo and @Tiger-man  you need to follow the manual link steps from the readme. After this, everything works fine :)

**Comment by paolitaclo** [comment]
I followed this step: select your project → Build Settings → Search Paths → Header Search Paths to add:

$(SRCROOT)/../node_modules/react-native-splash-screen/ios

![image](https://user-images.githubusercontent.com/8888095/61743282-ce7c9600-ad49-11e9-8e1a-a86b4884d4c3.png)
 but still getting the error: 
![image](https://user-images.githubusercontent.com/8888095/61743420-1ef3f380-ad4a-11e9-8adb-9451dd4106fb.png)
 I tried first installing the latest `react-native-splash-screen` version and then `pod install`, and then also tried downgraded the library to the `3.0.6` version and run `pod install` again.
Can Anyone help me with this please?

**Comment by wongcoder** [comment]
SplashScreen was renamed to RNSplashScreen. There are so many different versions running around that I have to change AppDelegate.m weekly.

**Comment by jhoanborges** [comment]
same problem

**Comment by rajeshde** [comment]
> I followed this step: select your project → Build Settings → Search Paths → Header Search Paths to add:
> 
> `$(SRCROOT)/../node_modules/react-native-splash-screen/ios`
> 
> ![image](https://user-images.githubusercontent.com/8888095/61743282-ce7c9600-ad49-11e9-8e1a-a86b4884d4c3.png)
> but still getting the error:
> ![image](https://user-images.githubusercontent.com/8888095/61743420-1ef3f380-ad4a-11e9-8adb-9451dd4106fb.png)
> I tried first installing the latest `react-native-splash-screen` version and then `pod install`, and then also tried downgraded the library to the `3.0.6` version and run `pod install` again.
> Can anyone help me with this, please?

I have done the same. Facing this issue after upgrading React Native to 0.60.4

In android it is auto linked, and works fine. Facing the same issue in iOS

**Comment by devilabhi** [comment]
i am also facing issue in iOS. I am using version 3.2.0 and react-native version 0.60.5

**Comment by tusharmutreja** [comment]
@devilabhi did you find any solution for this?

**Comment by salbatore** [comment]
The same problem today :P

**Comment by devilabhi** [comment]
I followed this step: select your project → Build Settings → Search Paths → Header Search Paths to add:

$(SRCROOT)/../node_modules/react-native-splash-screen/ios

then in terminal

cd ios
pod install
cd ..

**Comment by tusharmutreja** [comment]
It does not work for me, I am working with the latest version of RN 0.60.5

**Comment by CaptainJeff** [comment]
Anyone have a solution here?

**Comment by wongcoder** [comment]
@CaptainJeff I managed to solve it by reverting to a previous version of React Native splash screen. From then on, we refuse to upgrade react-native-splash-screen.

**Comment by CaptainJeff** [comment]
@wongcoder 

So weird! 

So you reverted to an older version of splash screen but then were you able to update react native?

What version of React Native splash screen did you revert back to?

**Comment by wongcoder** [comment]
Yeah, our teams codebase was rather fractured. One of us was using an older version of React Native Splash Screen, and another section of us was using a more modern version. We just jumped to the old one since it didnt' seem to have a performance issue. ^3.0.6 is our current version.

I was able to update React Native to 0.60.2, however, I haven't finished testing it on iOS (just Android) and that seemed to work alright.

**Comment by revanli** [comment]
same problem.
I am using version 3.2.1 and react-native version 0.61.1
after I downgrade version to `3.1.1` and reinstall node_modules, the problem solved !

rm -rf node_modules
npm install
cd ios && pod install

**Comment by ckOfor** [comment]
You need to addd this to your pod file: `"postinstall": "jetify && cd ios && pod check || pod install && cd .. && patch-package"`

**Comment by ckOfor** [comment]
You need to add this to your pod file: ``` pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'```

**Comment by yehyaumar** [comment]
I had this issue on my Mac M1 machine. I fixed it by adding this code to Pod file.
`post_install do |installer|
    installer.pods_project.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    react_native_post_install(installer)
  end
end`
Then
`cd ios
pod deintegrate
pod install
`

**Comment by toandn96** [comment]
> What version of React Native splash screen


Hi @yehyaumar, what version of React Native splash screen do you use?
