### ISSUE TITLE
 WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.

### ISSUE THREAD

**Issue by youngjuning** [crazycodeboy/react-native-splash-screen#327]
请问是否考虑升级以适用 0.57.*。 rn 0.57.* 已经提供了统一android support 的功能

![image](https://user-images.githubusercontent.com/13204332/47874880-f476a900-de4f-11e8-853e-29f00f716cee.png)

**Comment by heavyskyl** [comment]
@crazycodeboy , can you please make this small commit and upload new version to npm ?

**Comment by GertJOdendaal** [comment]
@crazycodeboy , Would be awesome if this update was on npm

**Comment by AntAreS24** [comment]
This is now causing issues in Studio.

**Comment by ozanmanav** [comment]
please update this compilte to implementation :)
