### ISSUE TITLE
Where to put image files?

### ISSUE THREAD

**Issue by arnsa** [crazycodeboy/react-native-splash-screen#34]
Hello,

I am a little bit confused, but where exactly do I have to store my splash screen images for ios and android? And do they have to have a specific naming or anything like that? Thanks!

**Comment by caleb-tolu** [comment]
@arnsa in your  \android\app\src\main\res folder u will create some folders in there as drawable-* i.e drawable-hdpi, drawable-mdpi e.t.c. and in each folder u will add ur splash screen image according to their sizes.
Your folder structure should be like this 
|-- drawable-hdpi
|-- drawable-mdpi
....
|-- layout
|-- mipmap-hdpi
.....
|-- values

**Comment by raynoppe** [comment]
And where do we put the iOS images?

**Comment by Jacse** [comment]
@raynoppe you can manage those through XCode - take a look at having a `LaunchImage` in `.xcassets` or using `LaunchScreen.xib`

**Comment by alxvallejo** [comment]
If you have to manage the launch image through Xcode, what exactly is the benefit of this module?

**Comment by ronaldozanoni** [comment]
@alxvallejo this module is to you control when the SplashScreen should hide.
For example: When you start your app, you need to check in the local storage if the user is logged or not to decide where direct it, or you need to make some request etc.
With this module, you can hide the splashscreen only after that check, programmatically.
