### ISSUE TITLE
Two Icon on android

### ISSUE THREAD

**Issue by radjivF** [crazycodeboy/react-native-splash-screen#358]
Hi, 

when I have added the splash screen and build I have now two apps and two icons.

I suspect it is because I have two activities in the manifest file, any idea how to fix it ?

Cheers

```<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="au.com.luciditysoftware.lucidity.inform">

  <uses-permission android:name="android.permission.INTERNET" />
  <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>
  <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
  <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
  <uses-permission android:name="android.permission.RECORD_AUDIO"/>
  <uses-permission android:name="android.permission.CAMERA" />
  <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
  <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />

  <application android:name=".MainApplication" android:label="@string/app_name" android:icon="@mipmap/ic_launcher" android:allowBackup="true" android:theme="@style/AppTheme">

    <activity android:name=".SplashActivity" android:theme="@style/SplashTheme" android:label="@string/app_name">
      <intent-filter>
        <action android:name="android.intent.action.MAIN" />
        <category android:name="android.intent.category.LAUNCHER" />
      </intent-filter>
    </activity>

    <activity android:name=".MainActivity" android:label="@string/app_name" android:configChanges="keyboard|keyboardHidden|orientation|screenSize" android:screenOrientation="portrait" android:windowSoftInputMode="adjustResize" android:exported="true">

      <intent-filter>
        <action android:name="android.intent.action.MAIN" />
        <category android:name="android.intent.category.LAUNCHER" />
      </intent-filter>
    </activity>
    <meta-data android:name="io.fabric.ApiKey" android:value="8cc2b1dacabac9316512c3fd92f0aaeeae0b3d21" />
    <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
  </application>

</manifest>
```

![screenshot_20190205-093931](https://user-images.githubusercontent.com/5714138/52242273-54d32600-292a-11e9-8f4b-6608742f5701.jpg)

**Comment by ishigamii** [comment]
@radjivF didn't you change the package name ? I am pretty sure it's not related to the lib

**Comment by stnmonroe** [comment]
Remove

`<intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
 </intent-filter>`

from under

`<activity
               android:name=".MainActivity"...`

The `.SplashActivity`, if you followed the directions correctly, should handle that by redirecting.

**Comment by radjivF** [comment]
we had two launcher so we removed it and its all good now

**Comment by ansonyao** [comment]
I commented out <category android:name="android.intent.category.LAUNCHER" /> from the mainActivity and it seems to be alright now.

**Comment by MuhammadUmairghufran** [comment]
> we had two launcher so we removed it and its all good now

I'm facing same issue - but it's not working

**Comment by chiennv97** [comment]
remove 
`<intent-filter>`
`<action android:name="android.intent.action.MAIN" />`
           ` <category android:name="android.intent.category.LAUNCHER" />`
           ` <action android:name="android.intent.action.DOWNLOAD_COMPLETE"/>  `
     `   </intent-filter>` 
from file AndroidManifest.xml
