### ISSUE TITLE
duplicate symbol _OBJC_CLASS_$_RNSplashScreen i

### ISSUE THREAD

**Issue by hanwenbo** [crazycodeboy/react-native-splash-screen#376]
duplicate symbol _OBJC_CLASS_$_RNSplashScreen in:
    /Users/hanwenbo/Library/Developer/Xcode/DerivedData/nairenertao-aubkufeoxnzezxaaldrybkizmwep/Build/Products/Debug-iphonesimulator/react-native-splash-screen/libreact-native-splash-screen.a(RNSplashScreen.o)
    /Users/hanwenbo/Library/Developer/Xcode/DerivedData/nairenertao-aubkufeoxnzezxaaldrybkizmwep/Build/Products/Debug-iphonesimulator/libSplashScreen.a(RNSplashScreen.o)
duplicate symbol _OBJC_METACLASS_$_RNSplashScreen in:
    /Users/hanwenbo/Library/Developer/Xcode/DerivedData/nairenertao-aubkufeoxnzezxaaldrybkizmwep/Build/Products/Debug-iphonesimulator/react-native-splash-screen/libreact-native-splash-screen.a(RNSplashScreen.o)
    /Users/hanwenbo/Library/Developer/Xcode/DerivedData/nairenertao-aubkufeoxnzezxaaldrybkizmwep/Build/Products/Debug-iphonesimulator/libSplashScreen.a(RNSplashScreen.o)
ld: 2 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by hanwenbo** [comment]
"react-native-splash-screen": "^3.2.0",
"react-native": "0.58.6",

**Comment by hanwenbo** [comment]
podfile error

**Comment by SimonDrew2018** [comment]
@hanwenbo 
How did you fix this error?

**Comment by jhoanborges** [comment]
import `#import "RNSplashScreen.m"`  instead of `#import "RNSplashScreen.h" `
This fixed my issue after getting this error in this line `  [RNSplashScreen show]; `

**Comment by devilabhi** [comment]
@SimonDrew2018 could you please elaborate, how did you remove the library link?

**Comment by SimonDrew2018** [comment]
@devilabhi sorry for the delay replying. From what I can remember, In XCode, remove SplashScreen.xcodeproj. I then removed libSplashScreen.a from the linked libraries in my projects Build Phases. Once they were removed I ran my pod install again and linked the library back following exactly what it says in the manual installation documentation.

I hope that helps.

**Comment by ckOfor** [comment]
You need to addd this to your pod file: `"postinstall": "jetify && cd ios && pod check || pod install && cd .. && patch-package"`

**Comment by ckOfor** [comment]
You need to add this to your pod file: ``` pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'```
