### ISSUE TITLE
'RNSplashScreen.h' file not found

### ISSUE THREAD

**Issue by jedabero** [crazycodeboy/react-native-splash-screen#379]
I've followed all the Manual installation steps

![image](https://user-images.githubusercontent.com/3894629/54310505-86ca4e80-45a0-11e9-822c-bd264f9abd57.png)
and
![image](https://user-images.githubusercontent.com/3894629/54310554-a5304a00-45a0-11e9-9c36-10470eef8567.png)
(tried both recursive and non-recursive)

And I'm still getting the error

**Comment by jedabero** [comment]
I'm really sorry it seems some additional charactes where pasted when doing the last step, has to go to the `ios/APP/APP.xcodeproj/project.pbxpfoj` file and remove the characters

**Comment by shanada** [comment]
![Screen Shot 2020-02-03 at 11 57 44](https://user-images.githubusercontent.com/28356820/73626786-cdbfa780-467c-11ea-8a10-95bf07b14e4b.png)


i solved with this documentary
