### ISSUE TITLE
App gets stuck on splash screen in release build ios

### ISSUE THREAD

**Issue by KristineTrona** [crazycodeboy/react-native-splash-screen#400]
**Run `react-native info` in your project and share the content.**

```
  React Native Environment Info:
    System:
      OS: macOS 10.14.4
      CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
      Memory: 43.92 MB / 8.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 12.1.0 - /usr/local/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 23, 24, 25, 26, 27, 28
        Build Tools: 27.0.3, 28.0.3
        System Images: android-28 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.4 AI-183.5429.30.34.5452501
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.8.3 => 16.8.6
      react-native: ^0.59.5 => 0.59.5
    npmGlobalPackages:
      create-react-native-app: 2.0.2
      react-native-cli: 2.0.1
```
**What `react-native-splash-screen` version are you using?**

  "react-native-splash-screen": "^3.2.0"

**What platform does your issue occur on? (Android/iOS/Both)**

iOS, but I do not know about android behaviour, as the app currently is made only for iOS

**Describe your issue as precisely as possible :** 

If I create a debug build iOS splash screen persists until the app is loaded and then is dimissed, however when I create a release build the app gets stuck on Splash screen. Any idea what might be causing it? In my App.js I am also using redux persist, and react navigation in my project. 

My code in Appdelegate.m:
```
...
 [RNSplashScreen show];
  return YES;
}
```

And hiding it in my root App.js component:

```
  componentDidMount() {
    SplashScreen.hide();
  }

  componentDidCatch(error, info) {
    SplashScreen.hide();
    ...
  }
```

Thank you in advance! Any help is very much appreciated!

**Comment by KristineTrona** [comment]
The issue in my case seems to be caused by something else in the project, so I do not think it is related to the library.

**Comment by ShaharyarMaroof** [comment]
@KristineTrona did you find your issue? I'm also facing the same thing, but cant trace the issue. Any help would be appreciated.

**Comment by mehul2013** [comment]
I m also facing this issue in iOS app only. Sometime it's working fine but sometime app gets stuck & crash. Let me know if anyone have solution.
