### ISSUE TITLE
iOS: Autolinking Not Working

### ISSUE THREAD

**Issue by cbothra** [crazycodeboy/react-native-splash-screen#414]
` error React Native CLI uses autolinking for native dependencies, but the following modules are linked manually: 

  - react-native-splash-screen (to unlink run: "react-native unlink react-native-splash-screen")
This is likely happening when upgrading React Native from below 0.60 to 0.60 or above. Going forward, you can unlink this dependency via "react-native unlink <dependency>" and it will be included in your app automatically. If a library isn't compatible with autolinking, disregard this message and notify the library maintainers.
Read more about autolinking: https://github.com/react-native-community/cli/blob/master/docs/autolinking.md`

I keep getting this error whenever I build for iOS(react-native run ios). Even though I have not manually linked the library. I used `react-native link react-native-splash-screen` to link the library to both iOS and android.

**Comment by bayareacoder** [comment]
Someone should do a PR that adds a podspec file under the iOS folder so this package gets picked up for auto-linking wen you run  `pod install` on  Podfile that has the 'use native modules' script. Required for packages to auto-link with RN >= 0.60

**Comment by bayareacoder** [comment]
@cbothra with RN >= 0.60 you no longer need to manually link, either by importing the .xcodeproj or running react-native link. it is done automatically when you run `pod install` with a Podfile that has the script `use_native_modules` provided by RN. So unlink as it says in the instructions, then run `pod install` and you should see this module as a Pod. Just installed it; it works since it has a podspec.

**Comment by cbothra** [comment]
@bayareacoder Thanks for the revert. I will surely try this out. Does it get automatically linked on android too without using `react-native link` command?

**Comment by bayareacoder** [comment]
Yes it should. 
Reference: https://github.com/react-native-community/cli/blob/master/docs/autolinking.md <https://github.com/react-native-community/cli/blob/master/docs/autolinking.md>

**Comment by cbothra** [comment]
Thanks @bayareacoder, I confirm that following your steps the warning message is gone and plugin is working fine on both iOS and android.
