### ISSUE TITLE
Splash screen does not show on build apk.

### ISSUE THREAD

**Issue by lewatt23** [crazycodeboy/react-native-splash-screen#416]
Run `react-native info` in your project and share the content.
```
React Native Environment Info:
    System:
      OS: Linux 5.0 Ubuntu 18.04.3 LTS (Bionic Beaver)
      CPU: (4) x64 Intel(R) Core(TM) i7-3540M CPU @ 3.00GHz
      Memory: 192.05 MB / 7.70 GB
      Shell: 4.4.20 - /bin/bash
    Binaries:
      Node: 10.16.2 - /usr/bin/node
      Yarn: 1.17.3 - /usr/bin/yarn
      npm: 6.9.0 - /usr/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      Android SDK:
        API Levels: 18, 19, 22, 23, 27, 28, 29
        Build Tools: 28.0.3, 29.0.1
        System Images: android-19 | Intel x86 Atom, android-22 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom, android-27 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-29 | Intel x86 Atom_64
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.8 => 0.59.8 
    npmGlobalPackages:
      react-native-debugger: 1.1.0

```

What `react-native-splash-screen` version are you using?
` "react-native-splash-screen": "^3.2.0",`

What platform does your issue occur on? (Android/iOS/Both)
Android

Describe your issue as precisely as possible : 
Hello everyone, Please just got this problem where, react-native-splash-screen works on android emulator well but does not work on release apk. on build apk i get a white screen instead of the splash screen, can some relate to this ?

**Comment by sasclau** [comment]
Same issue, crush on real device but work on simulator, on windows 10

**Comment by lewatt23** [comment]
@sasclau  found a solution ?

**Comment by sasclau** [comment]
Yes, somehow is not splashscreen the problem, was react.gradle, just go to react-native and download react.gradle file. Now is working fine

**Comment by luisneto98** [comment]
hello, 
I still have this error, you managed to solve?

**Comment by lewatt23** [comment]
@luisneto98  i did not solve it, i had not choice to remove react-native-splash-screen
