### ISSUE TITLE
Android release apk crash on startup

### ISSUE THREAD

**Issue by thomasngataly** [crazycodeboy/react-native-splash-screen#426]
Hello my release apk is crashing on startup on my device. I tried everything found online but can't manage to resolve this issue..

react-native-info :

> System:
    OS: macOS 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 457.85 MB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 8.16.0 - /usr/local/bin/node
    Yarn: 1.12.3 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
  SDKs:
    iOS SDK:
      Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
  IDEs:
    Xcode: 10.3/10G8 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6
    react-native: 0.60.4 => 0.60.4
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native-vector-icons: 6.6.0`

react-native-splash-screen version : 3.2.0 
Platform : Android

Here are the things i tried without success :
- I followed every steps of the setup
- `SplashScreen.show(this, true);` done
- `colors.xml `done
- `launch_screen.xml` done
- `mSplashDialog = new Dialog(activity, R.layout.launch_screen);` done

Here is the result of my logcat

> 09-13 19:01:47.932  3319  3357 E BufferQueueProducer: [com.sec.android.app.launcher/com.sec.android.app.launcher.activities.LauncherActivity[25445]#0] disconnect: not connected (req=1)
09-13 19:01:47.952  4016 11932 E WindowManager: win=Window{cd715f5 u0 com.sec.android.app.launcher/com.sec.android.app.launcher.activities.LauncherActivity} destroySurfaces: appStopped=false win.mWindowRemovalAllowed=false win.mRemoveOnExit=false win.mViewVisibility=8 caller=com.android.server.wm.WindowManagerService.tryStartExitingAnimation:2752 com.android.server.wm.WindowManagerService.relayoutWindow:2450 com.android.server.wm.Session.relayoutForTranslate:302 android.view.IWindowSession$Stub.onTransact:518 com.android.server.wm.Session.onTransact:186 android.os.Binder.execTransact:739 <bottom of call stack>
09-13 19:01:48.129 12666 12701 E ReactNativeJS: null is not an object (evaluating 'u.initialConstants')
09-13 19:01:48.138 12666 12701 E ReactNativeJS: Module AppRegistry is not a registered callable module (calling runApplication)
09-13 19:01:48.139 12666 12702 E AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
09-13 19:01:48.139 12666 12702 E AndroidRuntime: Process: com.company.xxxx, PID: 12666
09-13 19:01:48.139 12666 12702 E AndroidRuntime: com.facebook.react.common.JavascriptException: null is not an object (evaluating 'u.initialConstants'), stack:
09-13 19:01:48.139 12666 12702 E AndroidRuntime: <unknown>@526:1061
09-13 19:01:48.139 12666 12702 E AndroidRuntime: v@2:1474
09-13 19:01:48.139 12666 12702 E AndroidRuntime: <unknown>@524:141
09-13 19:01:48.139 12666 12702 E AndroidRuntime: v@2:1474
09-13 19:01:48.139 12666 12702 E AndroidRuntime: <unknown>@481:2142
09-13 19:01:48.139 12666 12702 E AndroidRuntime: v@2:1474
09-13 19:01:48.139 12666 12702 E AndroidRuntime: <unknown>@340:226
09-13 19:01:48.139 12666 12702 E AndroidRuntime: v@2:1474
09-13 19:01:48.139 12666 12702 E AndroidRuntime: <unknown>@6:58
09-13 19:01:48.139 12666 12702 E AndroidRuntime: v@2:1474
09-13 19:01:48.139 12666 12702 E AndroidRuntime: d@2:876
09-13 19:01:48.139 12666 12702 E AndroidRuntime: global code@1055:4
09-13 19:01:48.139 12666 12702 E AndroidRuntime:
09-13 19:01:48.139 12666 12702 E AndroidRuntime: 	at com.facebook.react.modules.core.ExceptionsManagerModule.showOrThrowError(ExceptionsManagerModule.java:54)
09-13 19:01:48.139 12666 12702 E AndroidRuntime: 	at com.facebook.react.modules.core.ExceptionsManagerModule.reportFatalException(ExceptionsManagerModule.java:38)
09-13 19:01:48.139 12666 12702 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-13 19:01:48.139 12666 12702 E AndroidRuntime: 	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
09-13 19:01:48.139 12666 12702 E AndroidRuntime: 	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
09-13 19:01:48.139 12666 12702 E AndroidRuntime: 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
09-13 19:01:48.139 12666 12702 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:873)
09-13 19:01:48.139 12666 12702 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
09-13 19:01:48.139 12666 12702 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
09-13 19:01:48.139 12666 12702 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
09-13 19:01:48.139 12666 12702 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:232)
09-13 19:01:48.139 12666 12702 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:764)
09-13 19:01:48.181 12731 12731 E Zygote  : isWhitelistProcess - Process is Whitelisted
09-13 19:01:48.182 12731 12731 E Zygote  : accessInfo : 1
09-13 19:01:48.190 12731 12731 E ng.android.loo: Not starting debugger since process cannot load the jdwp agent.
09-13 19:01:48.231 12454 12529 E PBSessionCacheImpl: sessionId[54774839643393225] not persisted.
09-13 19:01:48.258  4016  4135 E WindowManager: win=Window{f13e633 u0 Splash Screen com.company.xxxx EXITING} destroySurfaces: appStopped=false win.mWindowRemovalAllowed=true win.mRemoveOnExit=true win.mViewVisibility=0 caller=com.android.server.wm.AppWindowToken.destroySurfaces:870 com.android.server.wm.AppWindowToken.destroySurfaces:851 com.android.server.wm.WindowState.onExitAnimationDone:5399 com.android.server.wm.WindowStateAnimator.onAnimationFinished:319 com.android.server.wm.WindowState.onAnimationFinished:5821 com.android.server.wm.-$$Lambda$yVRF8YoeNdTa8GR1wDStVsHu8xM.run:2 com.android.server.wm.SurfaceAnimator.lambda$getFinishedCallback$0:97
09-13 19:01:48.285  3502  3502 E audit   : type=1400 audit(1568394108.282:57646): avc:  denied  { write } for  pid=12731 comm="ng.android.lool" name="com.samsung.android.lool-PMvGg3IGWyFo-7lRM1EwNQ==" dev="dm-1" ino=147614 scontext=u:r:system_app:s0 tcontext=u:object_r:apk_data_file:s0 tclass=dir permissive=0 SEPF_SM-G955F_9_0004 audit_filtered
09-13 19:01:48.285  3502  3502 E audit   : type=1300 audit(1568394108.282:57646): arch=c00000b7 syscall=48 success=no exit=-13 a0=ffffff9c a1=7c35cfaa40 a2=2 a3=0 items=0 ppid=3553 pid=12731 auid=4294967295 uid=1000 gid=1000 euid=1000 suid=1000 fsuid=1000 egid=1000 sgid=1000 fsgid=1000 tty=(none) ses=4294967295 comm="ng.android.lool" exe="/system/bin/app_process64" subj=u:r:system_app:s0 key=(null)
09-13 19:01:48.286  3502  3502 E audit   : type=1327 audit(1568394108.282:57646): proctitle="com.samsung.android.lool"
09-13 19:01:48.286  3502  3502 E audit   : type=1400 audit(1568394108.282:57647): avc:  denied  { write } for  pid=12731 comm="ng.android.lool" name="com.samsung.android.lool-PMvGg3IGWyFo-7lRM1EwNQ==" dev="dm-1" ino=147614 scontext=u:r:system_app:s0 tcontext=u:object_r:apk_data_file:s0 tclass=dir permissive=0 SEPF_SM-G955F_9_0004 audit_filtered
09-13 19:01:48.286  3502  3502 E audit   : type=1300 audit(1568394108.282:57647): arch=c00000b7 syscall=56 success=no exit=-13 a0=ffffff9c a1=7c35c22fe0 a2=42 a3=1b6 items=0 ppid=3553 pid=12731 auid=4294967295 uid=1000 gid=1000 euid=1000 suid=1000 fsuid=1000 egid=1000 sgid=1000 fsgid=1000 tty=(none) ses=4294967295 comm="ng.android.lool" exe="/system/bin/app_process64" subj=u:r:system_app:s0 key=(null)
09-13 19:01:48.286  3502  3502 E audit   : type=1327 audit(1568394108.282:57647): proctitle="com.samsung.android.lool"
09-13 19:01:48.312  3319  3358 E NativeSemDvfsGpuManager: acquire:: Start
09-13 19:01:48.312  3319  3358 E NativeSemDvfsGpuManager: acquire:: timeout = 1000 mIsAcquired = 0  mTagName : SurfaceFlinger
09-13 19:01:48.313  3319  3358 E NativeCustomFrequencyManager: [NativeCFMS] BpCustomFrequencyManager::requestGPU()
09-13 19:01:48.313  3319  3358 E NativeSemDvfsGpuManager: acquire:: End
09-13 19:01:48.386  3319  3357 E Layer   : $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
09-13 19:01:48.386  3319  3357 E Layer   : Abnormal Layer [Screenshot Parent]
09-13 19:01:48.408  3319  4256 E Layer   : $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
09-13 19:01:48.408  3319  4256 E Layer   : Abnormal Layer [Screenshot Parent]
09-13 19:01:48.410  3319  3358 E BufferQueueProducer: [com.company.xxxx/com.company.xxxx.MainActivity[12666]#0] disconnect: not connected (req=1)
09-13 19:01:48.437  3319  3357 E BufferQueueProducer: [com.company.xxxx/com.company.xxxx.MainActivity[12666]#1] disconnect: not connected (req=1)
09-13 19:01:48.445  4016 15691 E WindowManager: win=Window{9b37d77 u0 com.company.xxxx/com.company.xxxx.MainActivity} destroySurfaces: appStopped=false win.mWindowRemovalAllowed=false win.mRemoveOnExit=false win.mViewVisibility=8 caller=com.android.server.wm.WindowManagerService.tryStartExitingAnimation:2752 com.android.server.wm.WindowManagerService.relayoutWindow:2450 com.android.server.wm.Session.relayoutForTranslate:302 android.view.IWindowSession$Stub.onTransact:518 com.android.server.wm.Session.onTransact:186 android.os.Binder.execTransact:739 <bottom of call stack>
09-13 19:01:48.505 12666 12701 E ReactNativeJS: Module AppRegistry is not a registered callable module (calling unmountApplicationComponentAtRootTag)
09-13 19:01:48.536 12666 12666 E WindowManager:
09-13 19:01:48.536 12666 12666 E WindowManager: android.view.WindowLeaked: Activity com.company.xxxx.MainActivity has leaked window DecorView@fdb5252[MainActivity] that was originally added here
09-13 19:01:48.536 12666 12666 E WindowManager: 	at android.view.ViewRootImpl.<init>(ViewRootImpl.java:701)
09-13 19:01:48.536 12666 12666 E WindowManager: 	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:365)
09-13 19:01:48.536 12666 12666 E WindowManager: 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:93)
09-13 19:01:48.536 12666 12666 E WindowManager: 	at android.app.Dialog.show(Dialog.java:470)
09-13 19:01:48.536 12666 12666 E WindowManager: 	at org.devio.rn.splashscreen.SplashScreen$1.run(SplashScreen.java:36)
09-13 19:01:48.536 12666 12666 E WindowManager: 	at android.app.Activity.runOnUiThread(Activity.java:6404)
09-13 19:01:48.536 12666 12666 E WindowManager: 	at org.devio.rn.splashscreen.SplashScreen.show(SplashScreen.java:27)
09-13 19:01:48.536 12666 12666 E WindowManager: 	at org.devio.rn.splashscreen.SplashScreen.show(SplashScreen.java:49)
09-13 19:01:48.536 12666 12666 E WindowManager: 	at com.company.xxxx.MainActivity.onCreate(MainActivity.java:21)
09-13 19:01:48.536 12666 12666 E WindowManager: 	at android.app.Activity.performCreate(Activity.java:7327)
09-13 19:01:48.536 12666 12666 E WindowManager: 	at android.app.Activity.performCreate(Activity.java:7318)
09-13 19:01:48.536 12666 12666 E WindowManager: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
09-13 19:01:48.536 12666 12666 E WindowManager: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3094)
09-13 19:01:48.536 12666 12666 E WindowManager: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3257)
09-13 19:01:48.536 12666 12666 E WindowManager: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
09-13 19:01:48.536 12666 12666 E WindowManager: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
09-13 19:01:48.536 12666 12666 E WindowManager: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
09-13 19:01:48.536 12666 12666 E WindowManager: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1948)
09-13 19:01:48.536 12666 12666 E WindowManager: 	at android.os.Handler.dispatchMessage(Handler.java:106)
09-13 19:01:48.536 12666 12666 E WindowManager: 	at android.os.Looper.loop(Looper.java:214)
09-13 19:01:48.536 12666 12666 E WindowManager: 	at android.app.ActivityThread.main(ActivityThread.java:7050)
09-13 19:01:48.536 12666 12666 E WindowManager: 	at java.lang.reflect.Method.invoke(Native Method)
09-13 19:01:48.536 12666 12666 E WindowManager: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
09-13 19:01:48.536 12666 12666 E WindowManager: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
09-13 19:01:48.600 12780 12780 E Zygote  : isWhitelistProcess - Process is Whitelisted
09-13 19:01:48.601 12780 12780 E Zygote  : accessInfo : 1
09-13 19:01:48.608 12780 12780 E android.dqagen: Not starting debugger since process cannot load the jdwp agent.
09-13 19:01:48.808  4016  4135 E WindowManager: win=Window{f913611 u0 com.company.xxxx/com.company.xxxx.MainActivity EXITING} destroySurfaces: appStopped=false win.mWindowRemovalAllowed=true win.mRemoveOnExit=true win.mViewVisibility=8 caller=com.android.server.wm.AppWindowToken.destroySurfaces:870 com.android.server.wm.AppWindowToken.destroySurfaces:851 com.android.server.wm.WindowState.onExitAnimationDone:5399 com.android.server.wm.WindowStateAnimator.onAnimationFinished:319 com.android.server.wm.WindowState.onAnimationFinished:5821 com.android.server.wm.-$$Lambda$yVRF8YoeNdTa8GR1wDStVsHu8xM.run:2 com.android.server.wm.SurfaceAnimator.lambda$getFinishedCallback$0:97`

Any help ?
Thank you very much !

**Comment by thomasngataly** [comment]
closed since the error was elsewhere (caused by the facebook package).

**Comment by Malikkhoja** [comment]
Getting the same error.  @thomasngataly  How did you solve the error?

**Comment by DreamStarcoder** [comment]
E WindowManager: win=Window{66e4399 u0 Splash Screen com.cht EXITING} destroySurfaces: appStopped=false win.mWindowRemovalAllowed=true win.mRemoveOnExit=true win.mViewVisibility=0 caller=com.android.server.wm.AppWindowToken.destroySurfaces:896 com.android.server.wm.AppWindowToken.destroySurfaces:877 com.android.server.wm.WindowState.onExitAnimationDone:5479 com.android.server.wm.-$$Lambda$01bPtngJg5AqEoOWfW3rWfV7MH4.accept:2 java.util.ArrayList.forEach:1262 com.android.server.wm.AppWindowToken.onAnimationFinished:2469 com.android.server.wm.AppWindowToken.setVisibility:560

**Comment by edgardevwork** [comment]
у меня тож какая то странная ошибка [ru.edgar.space/ru.edgar.space.SAMP$_10691#0] disconnect: not connected (req=1)
win=Window{b102033 u0 ru.edgar.space/ru.edgar.space.SAMP EXITING} destroySurfaces: appStopped=false win.mWindowRemovalAllowed=true win.mRemoveOnExit=true win.mViewVisibility=0 caller=com.android.server.wm.AppWindowToken.destroySurfaces:1249 com.android.server.wm.AppWindowToken.destroySurfaces:1230 com.android.server.wm.WindowState.onExitAnimationDone:5189 com.android.server.wm.-$$Lambda$01bPtngJg5AqEoOWfW3rWfV7MH4.accept:2 java.util.ArrayList.forEach:1262 com.android.server.wm.AppWindowToken.onAnimationFinished:3941 com.android.server.wm.AppWindowToken.commitVisibility:914 
[ru.edgar.space/ru.edgar.space.SAMP$_10691#1] rejecting buffer: bufWidth=2960, bufHeight=1440, front.active_legacy.{w=1440, h=2960}
[ru.edgar.space/ru.edgar.space.SAMP$_10691#1] disconnect: not connected (req=1)
[ru.edgar.space/ru.edgar.space.SAMP$_10691#1] disconnect: not connected (req=1)

что делать?

на 9-10 андроиде крашит первый раз когда захожу второй нет

и так по кругу
