### ISSUE TITLE
RCTBridgeDelegate.h

### ISSUE THREAD

**Issue by musesfish** [crazycodeboy/react-native-splash-screen#428]
Run `react-native info` in your project and share the content.

What `react-native-splash-screen` version are you using?

What platform does your issue occur on? (Android/iOS/Both)

Describe your issue as precisely as possible : 
  1) Steps to reproduce the issue or to explain in which case you get the issue
  2) Interesting `logs`

Join a screenshot or video of the problem on the simulator or device?

Show us the code you are using?

**Comment by musesfish** [comment]
1. 'React/RCTBridgeDelegate.h' file not found
2."react-native-splash-screen": "^3.2.0",
   "react": "16.8.6",
   "react-native": "0.60.5",
3.ios

**Comment by musesfish** [comment]
> Run `react-native info` in your project and share the content.
> 
> What `react-native-splash-screen` version are you using?
> 
> What platform does your issue occur on? (Android/iOS/Both)
> 
> Describe your issue as precisely as possible :
> 
> 1. Steps to reproduce the issue or to explain in which case you get the issue
> 2. Interesting `logs`
> 
> Join a screenshot or video of the problem on the simulator or device?
> 
> Show us the code you are using?

**Comment by skay97** [comment]
@musesfish Were you able to solve this issue?
