### ISSUE TITLE
App crashes with React Native 0.61.2 on both iOS and Android

### ISSUE THREAD

**Issue by diogoguimaraes** [crazycodeboy/react-native-splash-screen#436]
```
System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 158.33 MB / 16.00 GB
    Shell: 5.7.1 - /usr/local/bin/zsh
  Binaries:
    Node: 12.11.1 - /usr/local/bin/node
    Yarn: 1.19.0 - /usr/local/bin/yarn
    npm: 6.11.3 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.0, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3, 29.0.2
      System Images: android-28 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5900203
    Xcode: 11.0/11A420a - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.2 => 0.61.2 
  npmGlobalPackages:
    react-native-cli: 2.0.1
```

`"react-native-splash-screen": "^3.2.0"`

What platform does your issue occur on? 
Both

The app crashes on launch with the following stack trace:
```
Invariant Violation: Module HMRClient is not a registered callable module (calling setup)
reportException @ ExceptionsManager.js:44
handleException @ ExceptionsManager.js:113
handleError @ setUpErrorHandling.js:23
reportFatalError @ error-guard.js:49
__guard @ MessageQueue.js:386
callFunctionReturnFlushedQueue @ MessageQueue.js:110
(anonymous) @ debuggerWorker.js:80
ExceptionsManager.js:44 Invariant Violation: Module RCTLog is not a registered callable module (calling logIfNoNativeHook)
reportException @ ExceptionsManager.js:44
handleException @ ExceptionsManager.js:113
handleError @ setUpErrorHandling.js:23
reportFatalError @ error-guard.js:49
__guard @ MessageQueue.js:386
callFunctionReturnFlushedQueue @ MessageQueue.js:110
(anonymous) @ debuggerWorker.js:80
ExceptionsManager.js:44 Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication)
```

**Comment by callcter** [comment]
same issue

**Comment by andylukmawan** [comment]
i use this library with RN v0.61.2 on [my repo](https://github.com/andylukmawan/react-native-starter), and it works.

**Comment by diogoguimaraes** [comment]
@andylukmawan have you made any specific change to whats in the documentation regarding installation and usage? Thanks!

**Comment by pabloluz** [comment]
@diogoguimaraes I was getting the same issue after migrating to RN 0.61.2 (actually, not only this, but many other libs got broken after migrating from RN 0.59.9).

So I decided to start a fresh RN project, install react-native-splash-screen and check if would it work... and it did work!

Although I can't precise what was the exact problem, I think it worth a try, since it only takes a few minutes...

And, if it works, I'd suggest you install/configure/build all your libs, one by one, to ensure that your stack is still working. At least, that's what I did and the splash screen is back again :)

**Comment by diogoguimaraes** [comment]
@pabloluz and @andylukmawan thanks for your feedback!

I started a fresh project and indeed it works. The only difference I have in my project is that I have a monorepo structure, so I'm assuming that the issue comes from there.

Thank you all.
