### ISSUE TITLE
No resource found that matches the given name (at 'background' with value '@drawable/launch_screen')

### ISSUE THREAD

**Issue by salauddinShaikh** [crazycodeboy/react-native-splash-screen#46]

**Comment by tishad770** [comment]
on your 'res' folder, create a 'drawable' folder. put your splash screen png file there and name it 'launch_screen.png'

**Comment by zjjaxx** [comment]
//remove
 
<ImageView android:layout_width="match_parent" android:layout_height="match_parent" android:src="@drawable/launch_screen" android:scaleType="centerCrop" />

//add
<ImageView android:layout_width="match_parent" android:layout_height="match_parent" android:src="@mipmap/launch_screen" android:scaleType="centerCrop" />

**Comment by NgocLe1001** [comment]
thank tishad770. you've saved my life
