### ISSUE TITLE
'React/RCTBridgeModule.h' file not found  error in react native splash screen

### ISSUE THREAD

**Issue by EhsanSarshar** [crazycodeboy/react-native-splash-screen#466]
System:
    OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz
    Memory: 356.16 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.13.0 - /usr/local/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 23, 25, 28, 29
      Build Tools: 28.0.3, 29.0.2
      System Images: android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.3.1/11C505 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1

react-native-splash-screen@^3.2.0

What platform does your issue occur on? (OS)

I just follow the steps to install the react-native-splash-screen
but after build I got this error

`'React/RCTBridgeModule.h' file not found`

```
/**
 * SplashScreen
 * 启动屏
 * from：http://www.devio.org
 * Author:CrazyCodeBoy
 * GitHub:https://github.com/crazycodeboy
 * Email:crazycodeboy@gmail.com
 */
#import <React/RCTBridgeModule.h>
#import <UIKit/UIKit.h>

@interface RNSplashScreen : NSObject<RCTBridgeModule>
+ (void)showSplash:(NSString*)splashScreen inRootView:(UIView*)rootView;
+ (void)show;
+ (void)hide;
@end
```

**The error is on line** **_9_**

**Comment by acmelacross** [comment]
'React/RCTBridgeModule.h' file not found


i have too error

**Comment by Ebeldev** [comment]
I had the same error. 

I fixed it by runn this command: cd ios && pod install && cd ..

And rerun npx react-native run-ios

**Comment by ysuMgl** [comment]
I have the same error

**Comment by acmelacross** [comment]
> I had the same error.
> 
> I fixed it by runn this command: cd ios && pod install && cd ..
> 
> And rerun npx react-native run-ios

cant resolve error，very sad。

**Comment by EhsanSarshar** [comment]
cd ios 
pod install
fix the issue

**Comment by Gazfay** [comment]
If you upgraded react-native to 0.60 >= - don't forget to remove react-native-splash-screen reference in Libraries folder!
