### ISSUE TITLE
Dark Mode Splash Screen Support Needed 

### ISSUE THREAD

**Issue by surajSanwal** [crazycodeboy/react-native-splash-screen#474]
how can I achieve differently splash for Dark and light mode?

**Comment by surajSanwal** [comment]
https://github.com/crazycodeboy/react-native-splash-screen/issues/475

**Comment by rvmaher** [comment]
[https://github.com/crazycodeboy/react-native-splash-screen/issues/475#issuecomment-1845884762](url)
