### ISSUE TITLE
fatal error: 'React/RCTBridgeModule.h' file not found

### ISSUE THREAD

**Issue by yangjiedage** [crazycodeboy/react-native-splash-screen#48]
in 'node_modules/react-native-splash-screen/ios/SplashScreen.h', '#import <React/RCTBridgeModule.h>', can not find the React/RCTBridgeModule.h file.How to fix this problem?

**Comment by farzer** [comment]
use the selected statement work for me

![image](https://cloud.githubusercontent.com/assets/9881593/24737454/6acc4b40-1ac1-11e7-9eec-205bce050b04.png)

**Comment by yangjiedage** [comment]
Thanks for your help!
