### ISSUE TITLE
Cannot read property 'hide' of null

### ISSUE THREAD

**Issue by sheywesk** [crazycodeboy/react-native-splash-screen#480]
Hi guys, I followed the readme: 
 
- Install package

- add Oncreate

- create launch_screen.xml

- call SplashScreen.hide() in componentDidMount

But I receive this error: 

> Cannot read property 'hide' of null

suggestions ? 

Im trying implements in open source project Jitsi-meet.

**Comment by sheywesk** [comment]
Resolved !

**Comment by herasymchuk** [comment]
@sheywesk I have the same issue. Could you please share your solution?

**Comment by sheywesk** [comment]
> @sheywesk I have the same issue. Could you please share your solution?

in jitsi-meet ?
you need add 
 `new org.devio.rn.splashscreen.SplashScreenReactPackage()`

in 
`android/sdk/src/main/java/org/jitsi/meet/sdk/ReactInstanceManagerHolder.java`

result

```
private static List<NativeModule> createNativeModules(ReactApplicationContext reactContext) {
      [...]
      new org.devio.rn.splashscreen.SplashScreenReactPackage()`
      [...]
 }
```

**Comment by herasymchuk** [comment]
@sheywesk thanks for prompting. Yep, it's jitsi-meet. But I had to add `new org.devio.rn.splashscreen.SplashScreenModule(reactContext)` to make it work. Anyway, you've saved me a lot of time!

**Comment by rachits21** [comment]
@herasymchuk @sheywesk Thanks guys for the resolution.
