### ISSUE TITLE
Error while using react-native-splash-screen with use_frameworks in podfile

### ISSUE THREAD

**Issue by Prince-Mittal** [crazycodeboy/react-native-splash-screen#518]
react-native-splash-screen version : 3.2.0
Issue Platform : iOS
Xcode Version : 12.4
react-native version : 0.63.3
react version: 16.13.1

<img width="585" alt="Issue-2" src="https://user-images.githubusercontent.com/43432878/109291301-d1593a00-784e-11eb-85b3-d7d40e9a698c.png">
<img width="271" alt="Issue-21" src="https://user-images.githubusercontent.com/43432878/109291313-d4ecc100-784e-11eb-8e27-82f33d15866a.png">

We want to use the splash screen in the project which is using use_frameworks in podfile. But it is causing linking issues. We have tried to add framework in the build Phases but still we are getting the same problem. I have added the screenshots of the issue shown in the xcode.

**Comment by mikehardy** [comment]
https://github.com/zoontek/react-native-bootsplash
