### ISSUE TITLE
App doens't start immediately when using windowIsTranslucent 

### ISSUE THREAD

**Issue by iLightFPS** [crazycodeboy/react-native-splash-screen#523]
When i press the app icon to start my app it takes like 2-3s before the app starts and the splash screen comes up.  This is only happening if i use item name="android:windowIsTranslucent">true</item in styles.xml. If i don't use this I get a white screen before the splash screen show up. 

This happens even if the app is in production mode.

Is there anyway to solve this?

**Comment by Sulaiman122** [comment]
same here

**Comment by dixithimanshu974** [comment]
Does anyone know how to resolve this issue?

**Comment by DavitVosk** [comment]
4 years passed, but still the same problem... Did you solve the problem @iLightFPS ?

**Comment by iLightFPS** [comment]
@DavitVosk Sorry i don't remember. I want to remember that i switched to another splash screen package but i could also have just downgraded to older version.
