### ISSUE TITLE
Why there are no code for ver 3.3.0, but this version is on npm registry?

### ISSUE THREAD

**Issue by Romick2005** [crazycodeboy/react-native-splash-screen#555]
I cannot see the differences between 3.2.0 and 3.3.0 in github.
In github latest version is 3.2.0, but in npm registry 3.3.0.
Can you please update this to actually see what was changed?

**Comment by TannerLessen** [comment]
https://github.com/crazycodeboy/react-native-splash-screen/commit/b47197626804a742b8569cad50d5e0ed92fc765c
It broke our code so just a heads up
