### ISSUE TITLE
How i can remove fade between native splash screen and the app React

### ISSUE THREAD

**Issue by matheussbarros** [crazycodeboy/react-native-splash-screen#560]
Run `react-native info` in your project and share the content.

What `react-native-splash-screen` version are you using?

What platform does your issue occur on? (Android/iOS/Both)

Describe your issue as precisely as possible : 
  1) Steps to reproduce the issue or to explain in which case you get the issue
  2) Interesting `logs`

Join a screenshot or video of the problem on the simulator or device?

Show us the code you are using?

**Comment by erickcrus** [comment]
How was the issue resolved?

**Comment by matheussbarros** [comment]
Na verdade nada foi feito, apenas segui a doc, e aceitei que a transição entre splash nativa e a splash dessa Lib tem comportamentos diferentes entre Android e IOS.

**Comment by erickcrus** [comment]
Eu comentei a linha 3 do arquivo ```node_modules/react-native-splash-screen/android/src/main/res/values/styles.xml```
```<resources>
    <style name="SplashScreen_SplashAnimation">
        <!--<item name="android:windowExitAnimation">@android:anim/fade_out</item>-->
    </style>
     ...
```
