### ISSUE TITLE
React-native 0.68.1 andorid SplashScreenReactPackage can't find it

### ISSUE THREAD

**Issue by HoSeopLee** [crazycodeboy/react-native-splash-screen#572]
I ran react-native-splash-screen and applied react-native link react-native-splash-screen.

When I try to build after applying, SplashScreen.show(this, R.style.SplashScreenTheme); I got a message saying the included SplashScreen could not be found. Is there any workaround for this? Please help me.
<img width="923" alt="image" src="https://user-images.githubusercontent.com/42264378/164699585-e929e47a-afea-4a94-992a-59456adf15fc.png">

**Comment by Adnan-Bacic** [comment]
the 3.3.0 version includes undocumented breaking changes, as seen here: https://github.com/crazycodeboy/react-native-splash-screen/issues/559 and https://github.com/crazycodeboy/react-native-splash-screen/issues/556

you basically just have to pass a 3rd `boolean` parameter to the `show()` function

**Comment by HoSeopLee** [comment]
> 3.3.0 버전에는 다음과 같이 문서화되지 않은 주요 변경 사항이 포함되어 있습니다. #559 및 #556
> 
> 기본적으로 함수 에 세 번째 `boolean`매개변수를 전달하면 됩니다.`show()`

thank you. Thanks it has been resolved. you will be blessed
