### ISSUE TITLE
Splash screen hides independently from hide.()

### ISSUE THREAD

**Issue by JuliaSzymanskaFirmao** [crazycodeboy/react-native-splash-screen#584]
Run `react-native info` in your project and share the content.
macOS Monterey 12.5.1

What `react-native-splash-screen` version are you using?
^3.3.0

What platform does your issue occur on? (Android/iOS/Both)
iOS

Regardless of whether or not I have not any .hide() methods or there are many of them, the splash screen hides in the same moment. I checked the installation process a couple of times, everything seems ok. Splash screen generally works but hides too early.

**Comment by anshif10** [comment]
Splash screen hides independently from hide.() only in ios  it's working fine in android .Please help..

System:
    OS: macOS 12.4
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
    Memory: 86.27 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 8.5.5 - /usr/local/bin/npm
    Watchman: 2022.09.19.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK:
      API Levels: 28, 29, 30, 31, 32, 33
      Build Tools: 23.0.1, 28.0.3, 29.0.2, 29.0.3, 30.0.2, 30.0.3, 31.0.0, 32.0.0, 32.1.0, 33.0.0
      System Images: android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-30 | Intel x86 Atom_64, android-31 | Google APIs Intel x86 Atom_64, android-Tiramisu | Google APIs Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.15 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: ^9.2.1 => 9.3.2 
    react: 18.1.0 => 18.1.0 
    react-native: ^0.70.5 => 0.70.6
