### ISSUE TITLE
Black Screen as splash screen in android

### ISSUE THREAD

**Issue by sachithamh** [crazycodeboy/react-native-splash-screen#585]
Run `react-native info` in your project and share the content.

System:
    OS: macOS 12.5.1
    CPU: (8) x64 Apple M1
    Memory: 28.04 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.17.6 - /usr/local/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 8.5.3 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8815526
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 18.0.1.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0 
    react-native: 0.69.4 => 0.69.4 
    react-native-macos: Not Found

What `react-native-splash-screen` version are you using? 

"react-native-splash-screen": "^3.3.0"

What platform does your issue occur on? (Android/iOS/Both)

Android

Describe your issue as precisely as possible : 

in Android App Splash functionality works but show a splash screen as Black Screen

Join a screenshot or video of the problem on the simulator or device?

simulator

**Comment by Watersdr** [comment]
I'm seeing this as well. Any luck with a solution?

**Comment by sachithamh** [comment]
> I'm seeing this as well. Any luck with a solution?

yes got it set the background color to android splash .XML default color is black
