### ISSUE TITLE
MainActivityDelegate cannot be converted to Activity SplashScreen.show(this);

### ISSUE THREAD

**Issue by ireneeming** [crazycodeboy/react-native-splash-screen#591]
Run `react-native info` in your project and share the content.
* Node : 16.17.0
* Yarn : 1.22.19
* react : 18.1.0
* react-native : 0.70.0

What `react-native-splash-screen` version are you using?
* "react-native-splash-screen": "^3.3.0",
What platform does your issue occur on? (Android/iOS/Both)
* just checked Android only.

Describe your issue as precisely as possible : 
  1) Steps to reproduce the issue or to explain in which case you get the issue

  2) Interesting `logs`

```
error: incompatible types: MainActivityDelegate cannot be converted to Activity
      SplashScreen.show(this);
```
more details of error
```
BUILD FAILED in 12s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081
/Users/minjiseo/buyaladdin/BRApp/BuyaladdinApp/android/app/src/main/java/com/aladdin/com/aladdin/MainActivity.java:59: error: incompatible types: MainActivityDelegate cannot be converted to Activity
      SplashScreen.show(this);
                        ^
Note: /Users/minjiseo/myFolder/MyAppName/AppName/android/app/src/debug/java/com/AppName/com/AppName/ReactNativeFlipper.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some messages have been simplified; recompile with -Xdiags:verbose to get full output
1 error
```

Join a screenshot or video of the problem on the simulator or device?

Show us the code you are using? 

followed the guide ```settings.gradle```, ```build.gradle```, ```App.tsx``` and set all done. 

### MainActivity.java
```
package com.aladdin.com.aladdin;

import android.app.Activity;
import android.os.Bundle;
import android.util.Log;
import android.widget.Toast;

import com.facebook.react.ReactActivity;
import com.facebook.react.ReactActivityDelegate;
import com.facebook.react.ReactRootView;
import com.lockincomp.liappagent.LiappAgent;

import org.devio.rn.splashscreen.SplashScreen;
...
@Override
    protected void onCreate(Bundle savedInstanceState) {

      SplashScreen.show(this);
  
     ...my other codes

      super.onCreate(null);
// super.onCreate(savedInstanceState); <- this also tried but not working
    }
```

I don't know why I'm having this kind of error. because of React Native 0.7 version error? or what,,,,please help..

**Comment by Guilleanto** [comment]
I have the same issue i'm using RN 0.70, maybe the new arch in RN 0.68 >?

**Comment by alejandro-technology** [comment]
I have the same mistake
* react: 18.1.0
* react-native: 0.70.4

@Guilleanto I think the new architecture is not enabled since the console does not see the message fabric:true. Only rootTag
![image](https://user-images.githubusercontent.com/46910469/198413313-5f9f3266-9109-4898-9c53-6d09ed107af9.png)

**Comment by GauthamChinna** [comment]
I have the same issue i'm using RN 0.70.4, is there any solution available?

**Comment by codersandipdas** [comment]
Add:  `import android.os.Bundle;` at the top of `MainActivity.java`

**Comment by bonusrk** [comment]
Fresh RN application MainActivity.java looks like so now:

```java
package com.myapp;

import android.os.Bundle;
import com.facebook.react.ReactActivity;
import org.devio.rn.splashscreen.SplashScreen;
import com.facebook.react.ReactActivityDelegate;
import com.facebook.react.ReactRootView;

public class MainActivity extends ReactActivity {

  /**
   * Returns the name of the main component registered from JavaScript. This is used to schedule
   * rendering of the component.
   */
  @Override
  protected String getMainComponentName() {
    return "MyApp";
  }

  /**
   * Returns the instance of the {@link ReactActivityDelegate}. There the RootView is created and
   * you can specify the renderer you wish to use - the new renderer (Fabric) or the old renderer
   * (Paper).
   */
  @Override
  protected ReactActivityDelegate createReactActivityDelegate() {
    return new MainActivityDelegate(this, getMainComponentName());
  }

  public static class MainActivityDelegate extends ReactActivityDelegate {
    public MainActivityDelegate(ReactActivity activity, String mainComponentName) {
      super(activity, mainComponentName);
    }

    @Override
    protected ReactRootView createRootView() {
      ReactRootView reactRootView = new ReactRootView(getContext());
      // If you opted-in for the New Architecture, we enable the Fabric Renderer.
      reactRootView.setIsFabric(BuildConfig.IS_NEW_ARCHITECTURE_ENABLED);
      return reactRootView;
    }

    @Override
    protected boolean isConcurrentRootEnabled() {
      // If you opted-in for the New Architecture, we enable Concurrent Root (i.e. React 18).
      // More on this on https://reactjs.org/blog/2022/03/29/react-v18.html
      return BuildConfig.IS_NEW_ARCHITECTURE_ENABLED;
    }

    @Override
    protected void onCreate(Bundle savedInstanceState) {
      SplashScreen.show(this);
      super.onCreate(null);
    }
  }
}
```
Still have the issue `incompatible types: MainActivityDelegate cannot be converted to Activity
      SplashScreen.show(this);`

method show goes from here
```java
    /**
     * 打开启动屏
     */
    public static void show(final Activity activity) {
        show(activity, false);
    }
```

and it take Activity type, while `this` in MainActivity is `MainActivityDelegate`

If we move `onCreate` outside of `MainActivityDelegate ` to the very top class application will be built successfully

**Comment by ireneeming** [comment]
@bonusrk I followed your guide, but mine doesn't work. 

```
package com.myapp.com.myapp;

import android.app.Activity;
import android.os.Bundle;
import android.util.Log;
import android.widget.Toast;

import com.facebook.react.ReactActivity;
import org.devio.rn.splashscreen.SplashScreen;
import com.facebook.react.ReactActivityDelegate;
import com.facebook.react.ReactRootView;
import com.lockincomp.liappagent.LiappAgent;

public class MainActivity extends ReactActivity {

  /**
   * Returns the name of the main component registered from JavaScript. This is used to schedule
   * rendering of the component.
   */
  @Override
  protected String getMainComponentName() {
    return "MyApp";
  }

  /**
   * Returns the instance of the {@link ReactActivityDelegate}. There the RootView is created and
   * you can specify the renderer you wish to use - the new renderer (Fabric) or the old renderer
   * (Paper).
   */

  @Override.    //<-------here is I added onCreate upper side but still doesn't work...is that right way I did?
  protected void onCreate(Bundle savedInstanceState) {
    SplashScreen.show(this);
    super.onCreate(null);
  }


  @Override
  protected ReactActivityDelegate createReactActivityDelegate() {
    return new MainActivityDelegate(this, getMainComponentName());
  }

  public static class MainActivityDelegate extends ReactActivityDelegate {
    public MainActivityDelegate(ReactActivity activity, String mainComponentName) {
      super(activity, mainComponentName);
    }

    @Override
    protected ReactRootView createRootView() {
      ReactRootView reactRootView = new ReactRootView(getContext());
      // If you opted-in for the New Architecture, we enable the Fabric Renderer.
      reactRootView.setIsFabric(BuildConfig.IS_NEW_ARCHITECTURE_ENABLED);
      return reactRootView;
    }

    @Override
    protected boolean isConcurrentRootEnabled() {
      // If you opted-in for the New Architecture, we enable Concurrent Root (i.e. React 18).
      // More on this on https://reactjs.org/blog/2022/03/29/react-v18.html
      return BuildConfig.IS_NEW_ARCHITECTURE_ENABLED;
    }

    @Override
    protected void onCreate(Bundle savedInstanceState) {

      ...my other codes which supposed to in this area
      super.onCreate(null);
    }
  }
}
```

**Comment by bonusrk** [comment]
> @bonusrk I followed your guide, but mine doesn't work.
> 
> ```
> package com.myapp.com.myapp;
> 
> import android.app.Activity;
> import android.os.Bundle;
> import android.util.Log;
> import android.widget.Toast;
> 
> import com.facebook.react.ReactActivity;
> import org.devio.rn.splashscreen.SplashScreen;
> import com.facebook.react.ReactActivityDelegate;
> import com.facebook.react.ReactRootView;
> import com.lockincomp.liappagent.LiappAgent;
> 
> public class MainActivity extends ReactActivity {
> 
>   /**
>    * Returns the name of the main component registered from JavaScript. This is used to schedule
>    * rendering of the component.
>    */
>   @Override
>   protected String getMainComponentName() {
>     return "MyApp";
>   }
> 
>   /**
>    * Returns the instance of the {@link ReactActivityDelegate}. There the RootView is created and
>    * you can specify the renderer you wish to use - the new renderer (Fabric) or the old renderer
>    * (Paper).
>    */
> 
>   @Override.    //<-------here is I added onCreate upper side but still doesn't work...is that right way I did?
>   protected void onCreate(Bundle savedInstanceState) {
>     SplashScreen.show(this);
>     super.onCreate(null);
>   }
> 
> 
>   @Override
>   protected ReactActivityDelegate createReactActivityDelegate() {
>     return new MainActivityDelegate(this, getMainComponentName());
>   }
> 
>   public static class MainActivityDelegate extends ReactActivityDelegate {
>     public MainActivityDelegate(ReactActivity activity, String mainComponentName) {
>       super(activity, mainComponentName);
>     }
> 
>     @Override
>     protected ReactRootView createRootView() {
>       ReactRootView reactRootView = new ReactRootView(getContext());
>       // If you opted-in for the New Architecture, we enable the Fabric Renderer.
>       reactRootView.setIsFabric(BuildConfig.IS_NEW_ARCHITECTURE_ENABLED);
>       return reactRootView;
>     }
> 
>     @Override
>     protected boolean isConcurrentRootEnabled() {
>       // If you opted-in for the New Architecture, we enable Concurrent Root (i.e. React 18).
>       // More on this on https://reactjs.org/blog/2022/03/29/react-v18.html
>       return BuildConfig.IS_NEW_ARCHITECTURE_ENABLED;
>     }
> 
>     @Override
>     protected void onCreate(Bundle savedInstanceState) {
> 
>       ...my other codes which supposed to in this area
>       super.onCreate(null);
>     }
>   }
> }
> ```

I think you should move `onCreate` totally. I mean delete it in nested class and keep only in top level.
I went event a little bit forward and kept only main class just to check and it works
```java
package com.myapp;

import android.os.Bundle;
import com.facebook.react.ReactActivity;
import org.devio.rn.splashscreen.SplashScreen;
import com.facebook.react.ReactActivityDelegate;
import com.facebook.react.ReactRootView;

public class MainActivity extends ReactActivity {

  /**
   * Returns the name of the main component registered from JavaScript. This is used to schedule
   * rendering of the component.
   */
  @Override
  protected String getMainComponentName() {
    return "MyApp";
  }

  @Override
  protected void onCreate(Bundle savedInstanceState) {
    SplashScreen.show(this);
    super.onCreate(null);
  }
}
```

**Comment by ireneeming** [comment]
@bonusrk 

now it works!!!!! Tnx very much!

**Comment by JslinSir** [comment]
<img width="721" alt="image" src="https://user-images.githubusercontent.com/30678791/202858369-ace2b980-3192-47fe-a5a7-e964b254ac0a.png">
Error still reported

```java
package com.driverapp;
import android.os.Bundle;
import com.facebook.react.ReactActivity;
import org.devio.rn.splashscreen.SplashScreen;
import com.facebook.react.ReactActivityDelegate;
import com.facebook.react.ReactRootView;



public class MainActivity extends ReactActivity {

  /**
   * Returns the name of the main component registered from JavaScript. This is used to schedule
   * rendering of the component.
   */
  @Override
  protected String getMainComponentName() {
    return "driverApp";
  }

  /**
   * Returns the instance of the {@link ReactActivityDelegate}. There the RootView is created and
   * you can specify the renderer you wish to use - the new renderer (Fabric) or the old renderer
   * (Paper).
   */
  @Override
  protected ReactActivityDelegate createReactActivityDelegate() {
    return new MainActivityDelegate(this, getMainComponentName());
  }

  public static class MainActivityDelegate extends ReactActivityDelegate {
    public MainActivityDelegate(ReactActivity activity, String mainComponentName) {
      super(activity, mainComponentName);
    }

    @Override
    protected ReactRootView createRootView() {
      ReactRootView reactRootView = new ReactRootView(getContext());
      // If you opted-in for the New Architecture, we enable the Fabric Renderer.
      reactRootView.setIsFabric(BuildConfig.IS_NEW_ARCHITECTURE_ENABLED);
      return reactRootView;
    }

    @Override
    protected boolean isConcurrentRootEnabled() {
      // If you opted-in for the New Architecture, we enable Concurrent Root (i.e. React 18).
      // More on this on https://reactjs.org/blog/2022/03/29/react-v18.html
      return BuildConfig.IS_NEW_ARCHITECTURE_ENABLED;
    }

    @Override
   protected void onCreate(Bundle savedInstanceState) {
      SplashScreen.show(this);
      super.onCreate(null);
   }

  }
}

```

**Comment by shahanshah87** [comment]
> @bonusrk
> 
> now it works!!!!! Tnx very much!

can you please share your final `MainActivity.java`

I tried like this:-
<img width="715" alt="Screenshot 2022-11-25 at 7 11 51 PM" src="https://user-images.githubusercontent.com/54522031/203997906-51237a39-558c-4ac7-bbae-cc106d992cab.png">


Build is successful but app is crashing.

**Comment by pedro-ernesto** [comment]
> 

You should pass null to super.onCreate

![image](https://user-images.githubusercontent.com/63816957/207374918-b6778da7-91f9-4721-9590-7daad04bce72.png)

**Comment by pedro-ernesto** [comment]
>> @Shahanshah87 
> can you please share your final `MainActivity.java`
> 
> Build is successful but app is crashing.

You should pass null to super.onCreate

![image](https://user-images.githubusercontent.com/63816957/207375097-6bc439d2-721b-425f-a81b-e15299b21828.png)

**Comment by pedro-ernesto** [comment]
> Error still reported

OnCreate should be outside MainActivityDelegate, check out my comment above

**Comment by pedro-ernesto** [comment]
> > @JslinSir 
> Error still reported

onCreate should be outside MainActivityDelegate, check out my comment above

**Comment by dleavittpmc** [comment]
@bonusrk You're the man! That did it. Thanks!
