### ISSUE TITLE
Crash on android, react-native 0.71.3 and react-native-splash-screen 3.3.0

### ISSUE THREAD

**Issue by lvothnrv** [crazycodeboy/react-native-splash-screen#608]
Hi, 
I have a problem with android my application bug. I'm running react-native 0.71.3 with react-native-splash-screen 3.3.0.
When I hide this part my application works but when I activate it, it crashes.
`  
@Override
  protected void onCreate(Bundle savedInstanceState) {
    SplashScreen.show(this);
    super.onCreate(savedInstanceState);
  }
`

**Comment by Tw-wT** [comment]
I have the same problem

**Comment by victororlyk** [comment]
I think this lib is not supported, according to code frequency

**Comment by nemo-qtopia** [comment]
I too have the same problem , App is crashing

**Comment by Buksirchik** [comment]
@lvothnrv could you give more details? Maybe share github link on your project or error log. Because in my project with 0.71.4 version, splash screen (3.3.0) works correctly.

**Comment by lvothnrv** [comment]
In my MainActivity.java
`import org.devio.rn.splashscreen.SplashScreen;

public class MainActivity extends ReactActivity {
  @Override
  protected void onCreate(Bundle savedInstanceState) {
    SplashScreen.show(this);
    super.onCreate(savedInstanceState);
  }
`

And in my build.gradle in the app 
`    implementation project(':react-native-splash-screen')`

**Comment by lvothnrv** [comment]
> @lvothnrv could you give more details? Maybe share github link on your project or error log. Because in my project with 0.71.4 version, splash screen (3.3.0) works correctly.

In my MainActivity.java
`
import org.devio.rn.splashscreen.SplashScreen;

public class MainActivity extends ReactActivity {
@OverRide
protected void onCreate(Bundle savedInstanceState) {
SplashScreen.show(this);
super.onCreate(savedInstanceState);
}
`

And in my build.gradle in the app
`
 implementation project(':react-native-splash-screen')
`

**Comment by Buksirchik** [comment]
@lvothnrv I see, you have done a manual installation. I would recommend you do the first step and the third step of installation guide. I don't need to do the second step (Manual installition)

**Comment by AFDHAL2009** [comment]
Hello , i have same issue  react native 0.70.6  
![227579507-031c0da0-59aa-4030-8ed5-b29f3e2336cd](https://user-images.githubusercontent.com/93435251/227582043-885eb6e5-8c76-4c60-8b38-ddb33cb12f4e.png)

**Comment by lvothnrv** [comment]
> @lvothnrv I see, you have done a manual installation. I would recommend you do the first step and the third step of installation guide. I don't need to do the second step (Manual installition)

The 3rd is it? 
`// react-native-splash-screen >= 0.3.1
import org.devio.rn.splashscreen.SplashScreenReactPackage;
// react-native-splash-screen < 0.3.1
import com.cboy.rn.splashscreen.SplashScreenReactPackage;

public class MainApplication extends Application implements ReactApplication {

    private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
        @Override
        public boolean getUseDeveloperSupport() {
            return BuildConfig.DEBUG;
        }

        @Override
        protected List<ReactPackage> getPackages() {
            return Arrays.<ReactPackage>asList(
                    new MainReactPackage(),
            new SplashScreenReactPackage()  //here
            );
        }
    };

    @Override
    public ReactNativeHost getReactNativeHost() {
        return mReactNativeHost;
    }
}`

**Comment by Buksirchik** [comment]
@lvothnrv  No, you need to look on the Third step(Plugin Configuration) section in a guide, not a third step of manual configuration. However, I'm trying to init project witn rn 0.71.3 and I'm gonna to set up splash screen 3.3.0 :D
I'm interested what can go wrong

**Comment by Buksirchik** [comment]
@lvothnrv I've launched rn 0.71.3 with react-native-splash-screen 3.3.0 and all works correctly 

This is the my test repo – https://github.com/Buksirchik/SplashScreen
This is the commit, where I added splash screen – https://github.com/Buksirchik/SplashScreen/commit/41219ad54204ced95ce4b19cf18b8ec66975feff
All works fine, there isn't a crash on android

https://user-images.githubusercontent.com/64099626/227663996-95c7631b-4970-470d-8cb1-9593379c0dac.mov

**Comment by lvothnrv** [comment]
> @lvothnrv I've launched rn 0.71.3 with react-native-splash-screen 3.3.0 and all works correctly
> 
> This is the my test repo – https://github.com/Buksirchik/SplashScreen This is the commit, where I added splash screen – [Buksirchik/SplashScreen@41219ad](https://github.com/Buksirchik/SplashScreen/commit/41219ad54204ced95ce4b19cf18b8ec66975feff) All works fine, there isn't a crash on android

You're going to insult me ​​my brother but in fact I'm going to make a mistake on the launch_screen.xml file I had written lauch_screen.xml and I checked your repository with my code and I saw that afterwards thank you aha

**Comment by AFDHAL2009** [comment]
any solution for    "react-native": "0.70.6"?

**Comment by AFDHAL2009** [comment]
this my activity 
import com.facebook.react.ReactActivity;
import com.facebook.react.ReactActivityDelegate;
import com.facebook.react.ReactRootView;
import android.os.Bundle;
import org.devio.rn.splashscreen.SplashScreenReactPackage;
import android.app.Activity;
public class MainActivity extends ReactActivity {
@Override
 
  /**

   * Returns the name of the main component registered from JavaScript. This is used to schedule
   * rendering of the component.
   */
  @Override
  protected String getMainComponentName() {
    return "_u";
  }

  /**
   * Returns the instance of the {@link ReactActivityDelegate}. There the RootView is created and
   * you can specify the renderer you wish to use - the new renderer (Fabric) or the old renderer
   * (Paper).
   */
  @Override
  protected ReactActivityDelegate createReactActivityDelegate() {
    return new MainActivityDelegate(this, getMainComponentName());
  }

  public static class MainActivityDelegate extends ReactActivityDelegate {
    public MainActivityDelegate(ReactActivity activity, String mainComponentName) {
   
      super(activity, mainComponentName);
        
    }
    

    @Override
    protected ReactRootView createRootView() {
       
      ReactRootView reactRootView = new ReactRootView(getContext());
      // If you opted-in for the New Architecture, we enable the Fabric Renderer.
      reactRootView.setIsFabric(BuildConfig.IS_NEW_ARCHITECTURE_ENABLED);
      return reactRootView;
    }

    @Override
    protected boolean isConcurrentRootEnabled() {
      // If you opted-in for the New Architecture, we enable Concurrent Root (i.e. React 18).
      // More on this on https://reactjs.org/blog/2022/03/29/react-v18.html
      return BuildConfig.IS_NEW_ARCHITECTURE_ENABLED;
    }

  
  }


}

**Comment by Buksirchik** [comment]
> any solution for "react-native": "0.70.6"?

I think, it's a same as for 0.71.3. Just check my message above and check commit in my test repo where I added a splash screen

**Comment by deepakaggarwal7** [comment]
> @lvothnrv I've launched rn 0.71.3 with react-native-splash-screen 3.3.0 and all works correctly
> 
> This is the my test repo – https://github.com/Buksirchik/SplashScreen This is the commit, where I added splash screen – [Buksirchik/SplashScreen@41219ad](https://github.com/Buksirchik/SplashScreen/commit/41219ad54204ced95ce4b19cf18b8ec66975feff) All works fine, there isn't a crash on android
> 
>  Screen.Recording.2023-03-25.at.02.54.47.mov

My app crashes when I try to  debug. Did your repo worked fine in debug mode?

**Comment by Buksirchik** [comment]
> My app crashes when I try to debug. Did your repo worked fine in debug mode?

Yes. It worked fine
