### ISSUE TITLE
Crash on iOS 16

### ISSUE THREAD

**Issue by usmanghani-em** [crazycodeboy/react-native-splash-screen#621]
Run `react-native info` in your project and share the content.
```
System:
  OS: macOS 13.4
  CPU: (10) arm64 Apple M2 Pro
  Memory: 94.83 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.16.0
    path: ~/.nvm/versions/node/v18.16.0/bin/node
  Yarn:
    version: 1.22.19
    path: ~/.nvm/versions/node/v18.16.0/bin/yarn
  npm:
    version: 9.5.1
    path: ~/.nvm/versions/node/v18.16.0/bin/npm
  Watchman:
    version: 2023.05.22.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.12.1
    path: /Users/usmanghani-em/.rbenv/shims/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.4
      - iOS 16.4
      - macOS 13.3
      - tvOS 16.4
      - watchOS 9.4
  Android SDK: Not Found
IDEs:
  Android Studio: 2022.2 AI-222.4459.24.2221.10121639
  Xcode:
    version: 14.3.1/14E300c
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.19
    path: /usr/bin/javac
  Ruby:
    version: 3.2.2
    path: /Users/usmanghani-em/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.1
    wanted: 0.72.1
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```
What `react-native-splash-screen` version are you using? `3.3.0`

What platform does your issue occur on? (Android/iOS/Both) `iOS`

Describe your issue as precisely as possible : 
  1) **Steps to reproduce the issue:** On calling `[RNSplashScreen show]` in `AppDelegate.mm`
  2) **Interesting `logs`**: Message from debugger: Terminated due to signal 9

Join a screenshot or video of the problem on the simulator or device?

<img width="1507" alt="image" src="https://github.com/crazycodeboy/react-native-splash-screen/assets/125430338/647efcf5-781a-4ef4-9052-0da7062c2e21">

Show us the code you are using? 

```
#import "RNSplashScreen.h"

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  self.moduleName = @"ZTAMobileAgent";
  // You can add your custom initial props in the dictionary below.
  // They will be passed down to the ViewController used by React Native.
  self.initialProps = @{};
// TODO: Fix this crash
  [RNSplashScreen show];
  return [super application:application didFinishLaunchingWithOptions:launchOptions];
}
```

**Comment by Serck96** [comment]
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  self.moduleName = @"ZTAMobileAgent";
  [super application:application didFinishLaunchingWithOptions:launchOptions];
  [RNSplashScreen show];
  
  return YES;
}
Try this code

**Comment by usmanghani-em** [comment]
> * (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
>   {
>   self.moduleName = @"ZTAMobileAgent";
>   [super application:application didFinishLaunchingWithOptions:launchOptions];
>   [RNSplashScreen show];
>   return YES;
>   }
>   Try this code

Moving this line `[super application:application didFinishLaunchingWithOptions:launchOptions];` above the `[RNSplashScreen show]` fixed the issue. Thank You 🚀
