### ISSUE TITLE
Android app is being crashed once I add SplashScreen.show(this, R.style.SplashScreenTheme, true); in my MainActivity.jsvs

### ISSUE THREAD

**Issue by mehedihsiam** [crazycodeboy/react-native-splash-screen#632]
Info: `
System:
  OS: Windows 11 10.0.22635
  CPU: (8) x64 Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz
  Memory: 625.23 MB / 7.88 GB
Binaries:
  Node:
    version: 20.9.0
    path: ~\AppData\Local\Temp\yarn--1700446503091-0.00899268766354866\node.CMD
  Yarn:
    version: 1.22.19
    path: ~\AppData\Local\Temp\yarn--1700446503091-0.00899268766354866\yarn.CMD
  npm:
    version: 10.1.0
    path: C:\Program Files\nodejs\npm.CMD
  Watchman: Not Found
SDKs:
  Android SDK: Not Found
  Windows SDK: Not Found
IDEs:
  Android Studio: AI-223.8836.35.2231.10811636
  Visual Studio: Not Found
Languages:
  Java: 11.0.21
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.7
    wanted: 0.72.7
  react-native-windows: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found
`

version: `"react-native-splash-screen": "^3.3.0",`

What platform does your issue occur on? : Android

**Problem: The app is being crashed.** 

1. I have installed the react-native-splash-screen and as it doesn't need to link anymore, that's why I didn't link it. 
2. I have created layout/launch_screen.xml
3. Added following lines in MainActivity.java `@Override
  protected void onCreate(Bundle savedInstanceState) {
      SplashScreen.show(this, R.style.SplashScreenTheme, true); 
      super.onCreate(null);
  }`

4. Aded `<style name="SplashScreenTheme" parent="SplashScreen_SplashTheme">
        <item name="colorPrimaryDark">@color/status_bar_color</item>
    </style>` in values/styles.xml

**Note: if I just hide `SplashScreen.show(this, R.style.SplashScreenTheme, true); `  from MainActivity.java then the app is working fine. **

**Comment by anatooly** [comment]
I think app not building with this code
```
error: incompatible types: int cannot be converted to boolean
      SplashScreen.show(this, R.style.SplashScreenTheme);
 ```
source code of method:
```
public static void show(final Activity activity, final boolean fullScreen) {
        int resourceId = fullScreen ? R.style.SplashScreen_Fullscreen : R.style.SplashScreen_SplashTheme;

        show(activity, resourceId, fullScreen);
    }
   ```

**Comment by mehedihsiam** [comment]
```
@Override
  protected void onCreate(Bundle savedInstanceState) {
      SplashScreen.show(this, R.style.SplashScreenTheme, true); 
      super.onCreate(null);
  }
```

This is the code. In my console, I can't see any error, app is also building perfectly but the is not opening in my device.

> I think app not building with this code
> 
> ```
> error: incompatible types: int cannot be converted to boolean
>       SplashScreen.show(this, R.style.SplashScreenTheme);
> ```
> 
> source code of method:
> 
> ```
> public static void show(final Activity activity, final boolean fullScreen) {
>         int resourceId = fullScreen ? R.style.SplashScreen_Fullscreen : R.style.SplashScreen_SplashTheme;
> 
>         show(activity, resourceId, fullScreen);
>     }
> ```

**Comment by mehedihsiam** [comment]
I was using XML file as launch_screen assets instead of PNG. Now it's working fine for me.

**Comment by FaresHamel** [comment]
@mehedihsiam can you explain that please ?
