### ISSUE TITLE
React native now use kotlin not java

### ISSUE THREAD

**Issue by omkero** [crazycodeboy/react-native-splash-screen#638]
I cant include splash screen into react native project, with 
old java code becuase my MainApplication file is kotlin not java  !!

**Comment by LongDuong1996** [comment]
package com.amessoeurs

import android.os.Bundle;
import com.facebook.react.ReactActivity
import com.facebook.react.ReactActivityDelegate
import com.facebook.react.defaults.DefaultNewArchitectureEntryPoint.fabricEnabled
import com.facebook.react.defaults.DefaultReactActivityDelegate
import org.devio.rn.splashscreen.SplashScreen;

class MainActivity : ReactActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        SplashScreen.show(this) // here
        super.onCreate(savedInstanceState)
    }

  /**
   * Returns the name of the main component registered from JavaScript. This is used to schedule
   * rendering of the component.
   */
  override fun getMainComponentName(): String = "amessoeurs"

  /**
   * Returns the instance of the [ReactActivityDelegate]. We use [DefaultReactActivityDelegate]
   * which allows you to enable New Architecture with a single boolean flags [fabricEnabled]
   */
  override fun createReactActivityDelegate(): ReactActivityDelegate =
      DefaultReactActivityDelegate(this, mainComponentName, fabricEnabled)
}

Change file MainActivity.kt.
Work for me!

**Comment by ivandjordjevicidjdev** [comment]
I have the same problem. I added SplashScreen.show(this) before super.onCreate(savedInstanceState) and it still doesn't work.

**Comment by Nziranziza** [comment]
same issue

**Comment by omarker09** [comment]
> I have the same problem. I added SplashScreen.show(this) before super.onCreate(savedInstanceState) and it still doesn't work.

**Comment by omarker09** [comment]
That's Why I will quit React native because this framework doesn't have any Official support it based on open source community I'm trying now to learn kotlin and work with android studio no more React native

**Comment by Nziranziza** [comment]
> That's Why I will quit React native because this framework doesn't have any Official support it based on open source community I'm trying now to learn kotlin and work with android studio no more React native 

Let's give it time the owner will eventually have to update to support Kotlin. Again Kotlin isn't an alternative to React Native maybe checkout Flutter instead

**Comment by AkilUnik** [comment]
package com.turtlebuddy
import android.os.Bundle;
import com.facebook.react.ReactActivity
import com.facebook.react.ReactActivityDelegate
import com.facebook.react.defaults.DefaultNewArchitectureEntryPoint.fabricEnabled
import com.facebook.react.defaults.DefaultReactActivityDelegate
// react-native-splash-screen >= 0.3.1

import org.devio.rn.splashscreen.SplashScreen;

class MainActivity : ReactActivity() {

  /**
   * Returns the name of the main component registered from JavaScript. This is used to schedule
   * rendering of the component.
   */
   override fun onCreate(savedInstanceState: Bundle?) {
    SplashScreen.show(this);  
    super.onCreate(null)
  }

  override fun getMainComponentName(): String = "turtleBuddy"

  /**
   * Returns the instance of the [ReactActivityDelegate]. We use [DefaultReactActivityDelegate]
   * which allows you to enable New Architecture with a single boolean flags [fabricEnabled]
   */
  override fun createReactActivityDelegate(): ReactActivityDelegate =
      DefaultReactActivityDelegate(this, mainComponentName, fabricEnabled)
}

**Comment by santimone** [comment]
> package com.turtlebuddy import android.os.Bundle; import com.facebook.react.ReactActivity import com.facebook.react.ReactActivityDelegate import com.facebook.react.defaults.DefaultNewArchitectureEntryPoint.fabricEnabled import com.facebook.react.defaults.DefaultReactActivityDelegate // react-native-splash-screen >= 0.3.1
> 
> import org.devio.rn.splashscreen.SplashScreen;
> 
> class MainActivity : ReactActivity() {
> 
> /**
> 
> * Returns the name of the main component registered from JavaScript. This is used to schedule
> * rendering of the component.
>   */
>   override fun onCreate(savedInstanceState: Bundle?) {
>   SplashScreen.show(this);
>   super.onCreate(null)
>   }
> 
> override fun getMainComponentName(): String = "turtleBuddy"
> 
> /**
> 
> * Returns the instance of the [ReactActivityDelegate]. We use [DefaultReactActivityDelegate]
> * which allows you to enable New Architecture with a single boolean flags [fabricEnabled]
>   */
>   override fun createReactActivityDelegate(): ReactActivityDelegate =
>   DefaultReactActivityDelegate(this, mainComponentName, fabricEnabled)
>   }

works like a charm, thanks!

**Comment by muhammadalizkhan** [comment]
Its Not Working;
package com.splashscreenandappiconapp

import android.os.Bundle;
import com.facebook.react.ReactActivity
import com.facebook.react.ReactActivityDelegate
import com.facebook.react.defaults.DefaultNewArchitectureEntryPoint.fabricEnabled
import com.facebook.react.defaults.DefaultReactActivityDelegate

import org.devio.rn.splashscreen.SplashScreen;

class MainActivity : ReactActivity() {

/**

Returns the name of the main component registered from JavaScript. This is used to schedule
rendering of the component.
*/
override fun onCreate(savedInstanceState: Bundle?) {
SplashScreen.show(this);
super.onCreate(null)
}
  override fun getMainComponentName(): String = "SplashScreenAndAppIconApp"

/**

Returns the instance of the [ReactActivityDelegate]. We use [DefaultReactActivityDelegate]
which allows you to enable New Architecture with a single boolean flags [fabricEnabled]
*/
override fun createReactActivityDelegate(): ReactActivityDelegate =
DefaultReactActivityDelegate(this, mainComponentName, fabricEnabled)
}

**Comment by bkvaiude** [comment]
Following code worked for me

```  
override fun createReactActivityDelegate(): ReactActivityDelegate {
      SplashScreen.show(this)
      return DefaultReactActivityDelegate(this, mainComponentName, fabricEnabled)
  }
```

**Comment by shariqahmed525** [comment]
> Following code worked for me
> 
> ```
> override fun createReactActivityDelegate(): ReactActivityDelegate {
>       SplashScreen.show(this)
>       return DefaultReactActivityDelegate(this, mainComponentName, fabricEnabled)
>   }
> ```

Thanks, it worked for me @bkvaiude

**Comment by i-ked-ii** [comment]
> Following code worked for me
> 
> ```
> override fun createReactActivityDelegate(): ReactActivityDelegate {
>       SplashScreen.show(this)
>       return DefaultReactActivityDelegate(this, mainComponentName, fabricEnabled)
>   }
> ```

Thanks, it worked.

**Comment by Ajmal0197** [comment]
Its working, This is my `MainActivity.kt`

```
package com.shiftusedcars

import com.facebook.react.ReactActivity
import com.facebook.react.ReactActivityDelegate
import com.facebook.react.defaults.DefaultNewArchitectureEntryPoint.fabricEnabled
import com.facebook.react.defaults.DefaultReactActivityDelegate

///////
import org.devio.rn.splashscreen.SplashScreen;
import android.os.Bundle;
///////

class MainActivity : ReactActivity() {

  override fun getMainComponentName(): String = "ShiftUsedCars"

/////
  override fun createReactActivityDelegate(): ReactActivityDelegate {
    SplashScreen.show(this)
    return DefaultReactActivityDelegate(this, mainComponentName, fabricEnabled)
}
//////

}

```
