### ISSUE TITLE
white screen after SplashScreen.hide()

### ISSUE THREAD

**Issue by emekalites** [crazycodeboy/react-native-splash-screen#65]
on android, after the SplashScreen.hide(); my app transitions into a white screen before rendering the component. any ideas on how to stop this entirely.

**Comment by camux** [comment]
The same problem here

**Comment by phamhuyhoang95** [comment]
same here

**Comment by phamhuyhoang95** [comment]
It is not a problem please do Third step(Plugin Configuration)! I missed that step from my app and when I do it blank screen gone!

**Comment by chuson1996** [comment]
@emekalites can you confirm? So that we can close this issue.

**Comment by emekalites** [comment]
I checked and discovered that the issue has more to do with my code than the plugin. On my app the plugin works well if user is already signed in, but shows a white screen first immediately after splash screen ends if user is not signed into my app. I'll look more into this. Meanwhile I'll close the issue and reopen if necessary.
