### ISSUE TITLE
how to maintain splash screen for a few second?

### ISSUE THREAD

**Issue by extJo** [crazycodeboy/react-native-splash-screen#68]
setTimeout() is not work....
so guys, how do you maintain splash screen for a few second?

**Comment by parampaa11** [comment]
Same question..

Can i maintain a delay after splash screen? I think too fast..

**Comment by Jacse** [comment]
Please remember to close the issue if it has been resolved, @extJo 😄

**Comment by saadlatif75** [comment]
React native splash screen are not hide by setTimeOut MEthod JAvasCript
