### ISSUE TITLE
Image is squeezed on Android

### ISSUE THREAD

**Issue by orangecoloured** [crazycodeboy/react-native-splash-screen#70]
I noticed taht image is a bit squeezed because of the top and bottom bars and found a way to avoid it.

Here's how my launch_screen.xml looks like now:
```xml
<?xml version="1.0" encoding="utf-8"?>
<FrameLayout
  xmlns:android="http://schemas.android.com/apk/res/android"
  android:layout_width="match_parent"
  android:layout_height="match_parent"
  android:orientation="vertical"
>
  <ImageView 
    android:src="@drawable/launch_screen"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:scaleType="centerCrop"
  >
  </ImageView>
</FrameLayout>
```
I am no Android developer and if there's a way to optimize or simplify it, that would be great.

**Comment by Jacse** [comment]
I don't think this is an issue with `react-native-splash-screen` but rather just the way Android layouting works.

**Comment by orangecoloured** [comment]
@Jacse you are right.
But still the image is squeezed if you use the layout from the docs.
So I would at least place a note there.

**Comment by pavelpashkovsky** [comment]
same too

**Comment by dauane** [comment]
This works for me too. Perhaps they could add this in the docs for the library? I'm sure it would help a lot of other devs.

**Comment by DylanVann** [comment]
I ended up making my image square to make things work.

**Comment by drewg233** [comment]
Were you able to fix this? I am struggling with this too.

https://stackoverflow.com/questions/50705341/android-react-native-different-image-resizing

**Comment by Alexorz** [comment]
@orangecoloured Cool, thanks!

**Comment by mohamedabusrea** [comment]
It worked for me but I noticed that it increased the image ratio to force it to fill the screen like "background-size: cover" in CSS and I prefer "background-size: contain" so I changed those properties

`<?xml version="1.0" encoding="utf-8"?>
<FrameLayout
  xmlns:android="http://schemas.android.com/apk/res/android"
  android:layout_width="match_parent"
  android:layout_height="match_parent"
  android:orientation="vertical"
  android:background="@color/splashBackground"
>
  <ImageView 
    android:src="@drawable/launch_screen"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:scaleType="centerInside"
  >
  </ImageView>
</FrameLayout>`

**Comment by SnaiNeR** [comment]
Guys, I have a more flexible solution for changing the ratio of the picture, which is perfect for me - scaleType="fitCenter", but need set backgroundColor for empty space on scaling
`<?xml version="1.0" encoding="utf-8"?>
<FrameLayout
  xmlns:android="http://schemas.android.com/apk/res/android"
  android:layout_width="match_parent"
  android:layout_height="match_parent"
  android:orientation="vertical"
  android:background="@color/splashBackground"
>
  <ImageView 
    android:src="@drawable/shell_launch_background_image"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:scaleType="fitCenter"
  >
  </ImageView>
</FrameLayout>`

**Comment by orangecoloured** [comment]
This has been addressed in this [merge](https://github.com/crazycodeboy/react-native-splash-screen/pull/312).

**Comment by coderjoel** [comment]
@orangecoloured I used the code and this is the output. Any help is appreciated. When I add the match_parent attribute it messes up the logo by cropping it up. 

![Capture1](https://user-images.githubusercontent.com/16961710/57740289-05b53380-7685-11e9-8da3-91dfef8fbe11.PNG)
![Capture](https://user-images.githubusercontent.com/16961710/57740290-05b53380-7685-11e9-863c-3128fc9576eb.PNG)
 
```
<?xml version="1.0" encoding="utf-8"?>
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="#262626"
    android:orientation="vertical">

    <ImageView
        android:layout_width="220dp"
        android:layout_height="250dp"
        android:layout_gravity="center"
        android:layout_margin="100dp"
        android:scaleType="centerCrop"
        android:src="@drawable/ic_cw_logo_white"></ImageView>
</FrameLayout>
```

For me, it is flashing stretched, then in less than a second, it pops with the correct dimension. I am using SVG file which imported as XML in drawable.

**Comment by orangecoloured** [comment]
@coderjoel try to use a raster version of the image, `png` or `jpg`. According to your description the component updates itself once it is rendered and has screen dimensions.

**Comment by export-mike** [comment]
@SnaiNeR @mohamedabusrea what do your @drawable/<name_of_image>.xml look like?

**Comment by export-mike** [comment]
@orangecoloured I'm using a png. it shows stretched then a split second later it resizes to the correct size.

launch_screen.xml
```xml
<?xml version="1.0" encoding="utf-8"?>
<FrameLayout
  xmlns:android="http://schemas.android.com/apk/res/android"
  android:layout_width="match_parent"
  android:layout_height="match_parent"
  android:background="@color/splashscreen_bg"
  android:orientation="vertical"
>
  <ImageView 
    android:src="@drawable/background_splash"
    android:layout_width="50dp"
    android:layout_height="50dp"
    android:scaleType="centerCrop"
    android:layout_gravity="center"
    android:layout_centerHorizontal="true"
  >
  </ImageView>
</FrameLayout>
```


background_splash.xml

```xml
<?xml version="1.0" encoding="utf-8"?>
<layer-list xmlns:android="http://schemas.android.com/apk/res/android">

    <item
        android:drawable="@color/splashscreen_bg"/>

    <item
        android:width="50dp"
        android:height="50dp"
        android:drawable="@mipmap/splash_icon"
   />

</layer-list>
```

**Comment by export-mike** [comment]
Update: 

Ok I'm now doing this

```xml
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@drawable/background_splash"
    android:orientation="vertical">
</LinearLayout>
```

```xml
<?xml version="1.0" encoding="utf-8"?>
<layer-list xmlns:android="http://schemas.android.com/apk/res/android">

    <item
        android:drawable="@color/splashscreen_bg"/>
    <item>
      <bitmap
        android:gravity="center"
        android:src="@mipmap/splash_icon"
      />
    </item>
    <!-- <item
        android:drawable="@mipmap/splash_icon"
   /> -->

</layer-list>
```

I have quite a small logo so I set it in the center small with lots of whitespace in each mipmap

mipmap-mdpi = splash_icon.png
mipmap-hdpi = splash_icon@2x.png
mipmap-xhdpi = splash_icon@3x.png
mipmap-xxhdpi = splash_icon@3x.png
mipmap-xxxhdpi = splash_icon@3x.png

**Comment by rohail111** [comment]
I still have the issue first my splash screen is squeezed then it gets okay after that I get squeeze again...
version 3.2.0

Gradle version 3.4.2
