### ISSUE TITLE
1920*1080 png will cause error on Android

### ISSUE THREAD

**Issue by Symous** [crazycodeboy/react-native-splash-screen#92]
Hi, if I set a 1920*1080 image as splash screen, it will give me an error that 
```
java.lang.RuntimeException: Unable to start activity 
ComponentInfo{com.symousreact/com.symousreact.MainActivity}: android.view.InflateException: 
Binary XML file line #2: Binary XML file line #2: Error inflating class <unknown>
```
and after I change the a 640*1136 image, it works well.

**Comment by jeril10** [comment]
I'm able to use 1920*1080 images without any issues

**Comment by Salehjarad** [comment]
You can generate Splash screens and icons from here > [http://apetools.webprofusion.com/](url)
And in **Photoshop** or any G app u use , Make **2048x2048** image size and save it as **PNG**, with background color [ [ **[ not transparent ]**

**Comment by Symous** [comment]
@Salehjarad Thanks my friend.
